import { createContext, useContext, useState, useCallback } from 'react'

export type AdminLocale = 'ko' | 'vi' | 'en'

const STORAGE_KEY = 'gada_admin_locale'

function getInitialLocale(): AdminLocale {
  try {
    const stored = localStorage.getItem(STORAGE_KEY)
    if (stored === 'ko' || stored === 'vi' || stored === 'en') return stored
  } catch {}
  return 'ko'
}

interface LanguageContextValue {
  locale: AdminLocale
  setLocale: (locale: AdminLocale) => void
}

const LanguageContext = createContext<LanguageContextValue>({
  locale: 'ko',
  setLocale: () => {},
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<AdminLocale>(getInitialLocale)

  const setLocale = useCallback((next: AdminLocale) => {
    setLocaleState(next)
    try {
      localStorage.setItem(STORAGE_KEY, next)
    } catch {}
  }, [])

  return (
    <LanguageContext.Provider value={{ locale, setLocale }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}

// Simple flat translation map
export const ADMIN_TRANSLATIONS: Record<AdminLocale, Record<string, string>> = {
  ko: {
    'settings.title': '설정',
    'settings.language.title': '언어 설정',
    'settings.language.subtitle': '어드민 패널에 표시될 언어를 선택하세요',
    'settings.language.ko': '한국어',
    'settings.language.vi': 'Tiếng Việt',
    'settings.language.en': 'English',
    'settings.language.current_suffix': '(현재)',

    'nav.dashboard': '📊 대시보드',
    'nav.managers': '👔 관리자 승인',
    'nav.managers_promote': '➕ 관리자 직접 지정',
    'nav.workers': '👷 근로자 관리',
    'nav.jobs': '🏗️ 일자리 관리',
    'nav.sites': '🏗️ 현장 관리',
    'nav.companies': '🏢 건설사 관리',
    'nav.notifications': '🔔 알림 발송',
    'nav.admin_users': '🔑 어드민 계정',
    'nav.test_accounts': '🧪 테스트 계정',
    'nav.settings': '⚙️ 설정',

    'layout.change_password': '🔒 비밀번호 변경',
    'layout.logout': '로그아웃',
    'layout.role.super_admin': '슈퍼관리자',
    'layout.role.admin': '관리자',
    'layout.role.viewer': '뷰어',

    'layout.pw_modal.title': '비밀번호 변경',
    'layout.pw_modal.current': '현재 비밀번호',
    'layout.pw_modal.new': '새 비밀번호 (8자 이상)',
    'layout.pw_modal.confirm': '새 비밀번호 확인',
    'layout.pw_modal.cancel': '취소',
    'layout.pw_modal.submit': '변경',
    'layout.pw_modal.submitting': '변경 중...',
    'layout.pw_modal.success': '비밀번호가 변경되었습니다',
    'layout.pw_modal.ok': '확인',
    'layout.pw_modal.error_mismatch': '새 비밀번호가 일치하지 않습니다',
    'layout.pw_modal.error_min_length': '비밀번호는 8자 이상이어야 합니다',
    'layout.pw_modal.error_failed': '변경 실패',

    'common.loading': '로딩 중...',
    'common.demo_data': '데모 데이터',
    'common.demo_suffix': '— API 연결 후 실제 데이터가 표시됩니다',
    'common.save': '저장',
    'common.saving': '저장 중...',
    'common.cancel': '취소',
    'common.edit': '수정',
    'common.delete': '삭제',
    'common.detail': '상세',
    'common.detail_arrow': '상세 →',
    'common.back_to_list': '← 목록으로',
    'common.deactivate': '삭제',
    'common.deactivated': '삭제되었습니다',
    'common.saved': '수정되었습니다',
    'common.deleted': '삭제되었습니다',
    'common.not_registered': '미등록',
    'common.registered': '✓ 등록됨',
    'common.search': '검색',
    'common.searching': '검색 중...',
    'common.total_count': '총 {n}',
    'common.processing': '처리 중...',
    'common.save_failed': '저장 실패',
    'common.delete_failed': '삭제 실패',
    'common.none': '-',
    'common.created_at': '생성일',
    'common.updated_at': '수정일',
    'common.per_page': '개씩 보기',

    'managers.title': '관리자 승인',
    'managers.tab_pending': '대기 중',
    'managers.tab_approved': '승인됨',
    'managers.tab_rejected': '거부됨',
    'managers.col_name': '근로자 이름',
    'managers.col_phone': '전화번호',
    'managers.col_site': '현장명',
    'managers.col_status': '상태',
    'managers.col_joined': '가입일',
    'managers.status_pending': '대기 중',
    'managers.status_approved': '승인됨',
    'managers.status_rejected': '거부됨',
    'managers.revoke': '권한 해제',
    'managers.detail_arrow': '상세 →',
    'managers.empty': '해당하는 관리자가 없습니다',
    'managers.total': '총 {n}명',
    'managers.flash_approved': '✅ 관리자가 승인되었습니다.',
    'managers.flash_rejected': '❌ 관리자 신청이 거부되었습니다.',
    'managers.confirm_revoke': '이 관리자의 권한을 해제하시겠습니까?',

    'dashboard.title': '대시보드',
    'dashboard.pending_managers': '승인 대기 관리자',
    'dashboard.total_workers': '총 근로자',
    'dashboard.active_sites': '운영 중 현장',
    'dashboard.open_jobs': '모집 중 공고',
    'dashboard.table_pending_managers': '승인 대기 관리자',
    'dashboard.view_all': '전체 보기 →',
    'dashboard.col_name': '이름',
    'dashboard.col_phone': '전화번호',
    'dashboard.col_joined': '가입일',
    'dashboard.no_pending': '대기 중인 관리자가 없습니다',
    'dashboard.detail_arrow': '상세 →',

    'workers.title': '근로자 관리',
    'workers.register': '+ 근로자 등록',
    'workers.search_placeholder': '이름 또는 전화번호 검색...',
    'jobs.search_placeholder': '제목 또는 현장명 검색...',
    'sites.search_placeholder': '현장명, 주소 또는 건설사 검색...',
    'companies.search_placeholder': '건설사명 검색...',
    'workers.col_name': '이름',
    'workers.col_phone': '전화번호',
    'workers.col_region': '지역',
    'workers.col_id_verified': '신분증 인증',
    'workers.col_role': '권한',
    'workers.col_joined': '가입일',
    'workers.id_verified': '인증 완료',
    'workers.id_unverified': '미인증',
    'workers.role_manager': '관리자',
    'workers.role_worker': '근로자',
    'workers.empty': '근로자가 없습니다',
    'workers.total': '총 {n}명',
    'workers.registered': '근로자가 등록되었습니다',
    'workers.confirm_deactivate': '근로자를 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
    'workers.modal.title': '근로자 등록',
    'workers.modal.phone_label': '전화번호 *',
    'workers.modal.name_label': '이름 *',
    'workers.modal.register': '등록',
    'workers.modal.registering': '등록 중...',
    'workers.modal.register_failed': '등록 실패',

    'sites.title': '현장 관리',
    'sites.new': '+ 새 현장',
    'sites.empty': '등록된 현장이 없습니다',
    'sites.first_register': '+ 첫 번째 현장 등록',
    'sites.total': '총 {n}개 현장',
    'sites.col_name': '현장명',
    'sites.col_company': '건설사',
    'sites.col_address': '주소',
    'sites.col_status': '상태',
    'sites.col_manager': '현장 관리자',
    'sites.col_job_count': '공고 수',
    'sites.col_registered': '등록일',
    'sites.status_active': '운영 중',
    'sites.status_completed': '완료',
    'sites.status_paused': '일시중지',
    'sites.registered': '현장이 등록되었습니다',
    'sites.confirm_delete': '현장을 삭제하시겠습니까? 연결된 공고도 함께 삭제됩니다.',
    'sites.modal.edit_title': '현장 수정',
    'sites.modal.create_title': '새 현장 등록',
    'sites.modal.company': '건설사',
    'sites.modal.company_none': '선택 안함',
    'sites.modal.manager': '현장 관리자 *',
    'sites.modal.manager_placeholder': '이름 또는 전화번호로 검색...',
    'sites.modal.manager_required': '현장 관리자를 선택해주세요.',
    'sites.modal.site_name': '현장명 *',
    'sites.modal.address': '주소 *',
    'sites.modal.province': '성/지역 *',
    'sites.modal.district': '군/구',
    'sites.modal.site_type': '현장 유형',
    'sites.modal.site_type_placeholder': '예: 아파트, 상업, 도로...',
    'sites.modal.status': '상태',
    'sites.modal.save_edit': '수정 완료',
    'sites.modal.save_create': '등록',
    'sites.modal.saving': '저장 중...',
    'sites.detail.back': '← 현장 목록으로 돌아가기',
    'sites.detail.type': '유형',
    'sites.detail.company': '건설사',
    'sites.detail.manager': '현장 관리자',
    'sites.detail.contact': '연락처',
    'sites.detail.company_contact_title': '건설사 담당자 정보',
    'sites.detail.contact_person': '담당자',
    'sites.detail.phone': '전화번호',
    'sites.detail.email': '이메일',
    'sites.detail.jobs_title': '공고 목록',
    'sites.detail.no_jobs': '등록된 공고가 없습니다',
    'sites.detail.col_title': '공고명',
    'sites.detail.col_status': '상태',
    'sites.detail.col_work_date': '근무일',
    'sites.detail.col_wage': '일 노임',
    'sites.detail.col_applicants': '지원자수',
    'sites.detail.col_hired': '선발인원',
    'sites.detail.job_status_open': '모집 중',
    'sites.detail.job_status_closed': '마감',
    'sites.detail.job_status_draft': '임시저장',
    'sites.detail.count_suffix': '명',
    'sites.load_error': '현장 정보를 불러올 수 없습니다',

    'jobs.title': '일자리 관리',
    'jobs.new': '+ 새 일자리',
    'jobs.empty': '일자리가 없습니다',
    'jobs.first_register': '+ 첫 번째 일자리 등록',
    'jobs.total': '총 {n}건',
    'jobs.tab_all': '전체',
    'jobs.tab_open': '모집 중',
    'jobs.tab_filled': '마감',
    'jobs.tab_cancelled': '취소됨',
    'jobs.col_title': '공고 제목',
    'jobs.col_site': '현장명',
    'jobs.col_work_date': '근무일',
    'jobs.col_wage': '일 노임',
    'jobs.col_slots': '모집인원',
    'jobs.col_status': '상태',
    'jobs.status_open': '모집 중',
    'jobs.status_filled': '마감',
    'jobs.status_cancelled': '취소됨',
    'jobs.flash_created': '✅ 일자리가 등록되었습니다.',
    'jobs.flash_updated': '✅ 수정되었습니다.',
    'jobs.flash_deleted': '🗑️ 취소 처리되었습니다.',
    'jobs.confirm_cancel': '이 공고를 취소 처리하시겠습니까?',
    'jobs.slots_suffix': '명',
    'jobs.form.back': '← 목록으로',
    'jobs.form.title_new': '일자리 등록',
    'jobs.form.title_edit': '일자리 수정',
    'jobs.form.field_site': '현장 *',
    'jobs.form.site_placeholder': '선택...',
    'jobs.form.field_title': '공고 제목 *',
    'jobs.form.field_trade': '직종',
    'jobs.form.trade_none': '선택 안 함',
    'jobs.form.field_work_date': '근무일 *',
    'jobs.form.field_start_time': '시작 시간',
    'jobs.form.field_end_time': '종료 시간',
    'jobs.form.field_daily_wage': '일 노임 (₫) *',
    'jobs.form.field_slots_total': '모집 인원 *',
    'jobs.form.field_status': '상태',
    'jobs.form.field_description': '설명',
    'jobs.form.save_new': '등록',
    'jobs.form.save_edit': '수정 완료',
    'jobs.form.saving': '저장 중...',
    'jobs.form.save_failed': '저장 실패',
    'jobs.form.loading': '로딩 중...',

    'companies.title': '건설사 관리',
    'companies.subtitle': '현장과 연결될 건설사 정보를 관리합니다',
    'companies.new': '+ 새 건설사',
    'companies.empty': '등록된 건설사가 없습니다',
    'companies.first_register': '+ 첫 번째 건설사 등록',
    'companies.total': '총 {n}개 건설사',
    'companies.col_name': '건설사명',
    'companies.col_reg_no': '사업자등록번호',
    'companies.col_contact': '담당자',
    'companies.col_phone': '연락처',
    'companies.col_sites': '현장 수',
    'companies.col_signature': '서명',
    'companies.col_registered': '등록일',
    'companies.sites_suffix': '개',
    'companies.registered': '건설사가 등록되었습니다',
    'companies.confirm_delete': '건설사를 삭제하시겠습니까?',
    'companies.modal.edit_title': '건설사 수정',
    'companies.modal.create_title': '새 건설사 등록',
    'companies.modal.name': '건설사명 *',
    'companies.modal.reg_no': '사업자등록번호',
    'companies.modal.contact_name': '담당자명',
    'companies.modal.contact_phone': '담당자 전화번호',
    'companies.modal.contact_email': '담당자 이메일',
    'companies.modal.save_edit': '수정 완료',
    'companies.modal.save_create': '등록',
    'companies.modal.saving': '저장 중...',
    'companies.detail.back': '← 건설사 목록으로 돌아가기',
    'companies.detail.reg_no_label': '사업자등록번호: ',
    'companies.detail.contact': '담당자',
    'companies.detail.phone': '전화번호',
    'companies.detail.email': '이메일',
    'companies.detail.linked_sites': '연결된 현장',
    'companies.detail.linked_sites_suffix': '개',
    'companies.detail.signature': '건설사 서명 / 법인인감',
    'companies.detail.signature_alt': '건설사 서명',
    'companies.detail.no_signature': '서명 미등록',
    'companies.detail.reg_cert': '사업자등록증',
    'companies.detail.view_reg_cert': '📄 사업자등록증 보기',
    'companies.load_error': '건설사 정보를 불러올 수 없습니다',
    'companies.seal.upload': '이미지 등록',
    'companies.seal.change': '이미지 변경',
    'companies.seal.drop_hint': '클릭하여 이미지 업로드',
    'companies.seal.uploaded': '서명/법인인감이 등록되었습니다',
    'companies.seal.upload_failed': '업로드 실패. 다시 시도해주세요.',
    'companies.seal.deleted': '서명/법인인감이 삭제되었습니다',
    'companies.seal.confirm_delete': '서명/법인인감 이미지를 삭제하시겠습니까?',

    'test_accounts.title': '테스트 계정 관리',
    'test_accounts.subtitle': '고정 OTP(000000)로 로그인할 수 있는 테스트 전화번호를 관리합니다',
    'test_accounts.add': '+ 테스트 계정 추가',
    'test_accounts.empty': '등록된 테스트 계정이 없습니다',
    'test_accounts.otp_hint': '테스트 계정으로 등록된 전화번호는 인증번호 "000000"으로 로그인할 수 있습니다.',
    'test_accounts.col_phone': '전화번호',
    'test_accounts.col_name': '이름',
    'test_accounts.col_role': '권한',
    'test_accounts.col_status': '상태',
    'test_accounts.col_created': '등록일',
    'test_accounts.role_worker': '근로자',
    'test_accounts.role_manager': '관리자',
    'test_accounts.confirm_delete': '이 테스트 계정을 삭제하시겠습니까?',
    'test_accounts.deleted': '테스트 계정이 삭제되었습니다',
    'test_accounts.created': '테스트 계정이 등록되었습니다',
    'test_accounts.error_phone_required': '전화번호를 입력하세요',
    'test_accounts.error_create_failed': '등록 실패',
    'test_accounts.add_modal.title': '테스트 계정 추가',
    'test_accounts.add_modal.phone': '전화번호',
    'test_accounts.add_modal.name': '이름',
    'test_accounts.add_modal.name_placeholder': '예: 테스트 근로자',
    'test_accounts.add_modal.role': '권한',
    'test_accounts.add_modal.submit': '등록',

    'login.brand': '가다 VN',
    'login.error_credentials': '아이디 또는 비밀번호가 틀렸습니다.',
    'login.logout_success': '로그아웃 되었습니다.',
    'login.username': '아이디',
    'login.password': '비밀번호',
    'login.submit': '로그인',
    'login.submitting': '로그인 중...',

    'admin_users.title': '어드민 계정 관리',
    'admin_users.subtitle': '메뉴별 접근 권한을 설정하고 이메일로 계정을 초대합니다',
    'admin_users.invite': '+ 계정 초대',
    'admin_users.col_email': '이메일 / 이름',
    'admin_users.col_role': '등급',
    'admin_users.col_permissions': '메뉴 권한',
    'admin_users.col_status': '상태',
    'admin_users.col_last_login': '마지막 로그인',
    'admin_users.me': '나',
    'admin_users.status_active': '활성',
    'admin_users.status_invited': '초대 대기',
    'admin_users.status_disabled': '비활성',
    'admin_users.role_super_admin': '슈퍼관리자',
    'admin_users.role_admin': '관리자',
    'admin_users.role_viewer': '뷰어',
    'admin_users.action_edit_permissions': '권한 편집',
    'admin_users.action_reset_password': '비밀번호 재설정',
    'admin_users.action_resend': '재전송',
    'admin_users.action_disable': '비활성화',
    'admin_users.confirm_disable': '계정을 비활성화하시겠습니까?',
    'admin_users.disabled': '비활성화되었습니다',
    'admin_users.action_delete': '삭제',
    'admin_users.confirm_delete': '계정을 영구 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
    'admin_users.deleted': '계정이 삭제되었습니다',
    'admin_users.invite_issued': '초대 링크가 발급되었습니다',
    'admin_users.permissions_saved': '권한이 저장되었습니다',
    'admin_users.password_changed': '비밀번호가 변경되었습니다',
    'admin_users.invite_modal.title': '어드민 계정 초대',
    'admin_users.invite_modal.invite_done': '초대 링크 발급 완료',
    'admin_users.invite_modal.invite_instruction': '에게 초대 링크를 전달하세요.',
    'admin_users.invite_modal.invite_link_label': '초대 링크 (7일간 유효)',
    'admin_users.invite_modal.copy': '복사',
    'admin_users.invite_modal.close': '닫기',
    'admin_users.invite_modal.email': '이메일 *',
    'admin_users.invite_modal.name': '이름',
    'admin_users.invite_modal.name_placeholder': '홍길동',
    'admin_users.invite_modal.role': '등급 *',
    'admin_users.invite_modal.permissions': '메뉴 접근 권한',
    'admin_users.invite_modal.submit': '초대 링크 발급',
    'admin_users.invite_modal.submitting': '처리 중...',
    'admin_users.invite_modal.invite_failed': '초대 실패',
    'admin_users.invite_modal.email_sent': '초대 이메일이 전송되었습니다',
    'admin_users.invite_modal.email_not_sent': '이메일 전송 실패 — 아래 링크를 직접 전달해 주세요',
    'admin_users.permissions_modal.title': '권한 편집',
    'admin_users.permissions_modal.role': '등급',
    'admin_users.permissions_modal.permissions': '메뉴 접근 권한',
    'admin_users.permissions_modal.save': '저장',
    'admin_users.permissions_modal.saving': '저장 중...',
    'admin_users.permissions_modal.save_failed': '저장 실패',
    'admin_users.reset_pw_modal.title': '비밀번호 재설정',
    'admin_users.reset_pw_modal.new_password': '새 비밀번호',
    'admin_users.reset_pw_modal.new_password_placeholder': '8자 이상',
    'admin_users.reset_pw_modal.confirm': '비밀번호 확인',
    'admin_users.reset_pw_modal.submit': '비밀번호 재설정',
    'admin_users.reset_pw_modal.submitting': '변경 중...',
    'admin_users.reset_pw_modal.error_mismatch': '비밀번호가 일치하지 않습니다',
    'admin_users.reset_pw_modal.error_min_length': '비밀번호는 8자 이상이어야 합니다',
    'admin_users.reset_pw_modal.change_failed': '변경 실패',
    'admin_users.menu.dashboard': '📊 대시보드',
    'admin_users.menu.managers': '👔 관리자 승인',
    'admin_users.menu.workers': '👷 근로자 관리',
    'admin_users.menu.jobs': '🏗️ 일자리 관리',
    'admin_users.menu.sites': '🏢 현장 관리',
    'admin_users.menu.notifications': '🔔 알림 발송',
    'admin_users.menu.admin_users': '🔑 어드민 계정',

    'worker_detail.not_found': '근로자를 찾을 수 없습니다',
    'worker_detail.manager_badge': '관리자',
    'worker_detail.id_verified': '신분증 인증',
    'worker_detail.id_unverified': '미인증',
    'worker_detail.id_verified_badge': '인증됨',
    'worker_detail.id_unverified_badge': '미인증',
    'worker_detail.profile_complete': '프로필 완성',
    'worker_detail.id_verified_check': '신분증 인증',
    'worker_detail.confirm_deactivate': '근로자를 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.',
    'worker_detail.deactivate_failed': '삭제 실패',
    'worker_detail.save_success': '저장되었습니다.',
    'worker_detail.save_failed': '저장 실패. 다시 시도해주세요.',
    'worker_detail.skills_saved': '직종 기술이 저장되었습니다.',
    'worker_detail.tab_basic': '기본 정보',
    'worker_detail.tab_docs': '신분증 / 서류',
    'worker_detail.tab_bank': '은행 / 결제',
    'worker_detail.tab_trades': '직종 / 기술',
    'worker_detail.tab_manager': '관리자',
    'worker_detail.tab_misc': '기타',
    'worker_detail.tab_contracts': '계약서',
    'worker_detail.contracts_loading': '로딩 중...',
    'worker_detail.contracts_empty': '계약서가 없습니다.',
    'worker_detail.contracts_error': '계약서를 불러올 수 없습니다.',
    'worker_detail.contract_status_pending_worker_sign': '근로자 서명 대기',
    'worker_detail.contract_status_pending_manager_sign': '건설사 서명 대기',
    'worker_detail.contract_status_fully_signed': '계약 완료',
    'worker_detail.contract_status_void': '계약 무효',
    'worker_detail.contract_job_title': '일자리',
    'worker_detail.contract_site': '현장',
    'worker_detail.contract_work_date': '근무일',
    'worker_detail.contract_daily_wage': '일당',
    'worker_detail.contract_worker_signed': '근로자 서명',
    'worker_detail.contract_created_at': '생성일',
    'worker_detail.field_name': '이름',
    'worker_detail.field_dob': '생년월일',
    'worker_detail.field_gender': '성별',
    'worker_detail.field_gender_none': '선택 안 함',
    'worker_detail.field_gender_male': '남성',
    'worker_detail.field_gender_female': '여성',
    'worker_detail.field_gender_other': '기타',
    'worker_detail.field_bio': '자기소개',
    'worker_detail.field_trade_id': '주요 직종 ID',
    'worker_detail.field_experience': '경력 (개월)',
    'worker_detail.field_id_number': '주민등록번호 / ID 번호',
    'worker_detail.field_verified_at': '인증일',
    'worker_detail.unverified_date': '미인증',
    'worker_detail.attachments_title': '첨부 이미지',
    'worker_detail.field_id_front': '신분증 앞면',
    'worker_detail.field_id_back': '신분증 뒷면',
    'worker_detail.field_bank_book': '통장사본',
    'worker_detail.field_signature': '서명',
    'worker_detail.field_bank_name': '은행명',
    'worker_detail.field_bank_account': '계좌번호',
    'worker_detail.trades_loading': '로딩 중...',
    'worker_detail.trades_empty': '등록된 직종이 없습니다.',
    'worker_detail.trade_select': '직종 선택',
    'worker_detail.experience_years_placeholder': '경력(년)',
    'worker_detail.experience_years_suffix': '년',
    'worker_detail.trade_add': '+ 직종 추가',
    'worker_detail.manager_active': '관리자 활성',
    'worker_detail.approved_suffix': '승인)',
    'worker_detail.field_company': '회사명',
    'worker_detail.field_contact_name': '담당자명',
    'worker_detail.manager_profile_link': '관리자 프로필 상세 보기 →',
    'worker_detail.no_manager': '이 근로자는 관리자 권한이 없습니다.',
    'worker_detail.promote_link': '관리자로 지정하기 →',
    'worker_detail.field_phone': '전화번호',
    'worker_detail.field_email': '이메일',
    'worker_detail.field_lat': '위도 (lat)',
    'worker_detail.field_lng': '경도 (lng)',
    'worker_detail.terms_accepted': '이용약관 동의',
    'worker_detail.privacy_accepted': '개인정보 처리방침 동의',
    'worker_detail.field_joined': '가입일',

    'manager_detail.not_found': '관리자를 찾을 수 없습니다',
    'manager_detail.status_approved': '승인됨',
    'manager_detail.status_rejected': '반려됨',
    'manager_detail.status_revoked': '해제됨',
    'manager_detail.status_pending': '대기 중',
    'manager_detail.approve': '승인',
    'manager_detail.reject': '반려',
    'manager_detail.revoke': '권한 해제',
    'manager_detail.re_approve': '재심사 (승인 처리)',
    'manager_detail.confirm_approve': '승인하시겠습니까?',
    'manager_detail.confirm_revoke': '권한을 해제하시겠습니까?',
    'manager_detail.reject_reason_label': '반려 사유',
    'manager_detail.reject_reason_placeholder': '반려 사유를 입력하세요',
    'manager_detail.reject_confirm': '반려 확정',
    'manager_detail.reject_reason_required': '반려 사유를 입력해주세요.',
    'manager_detail.site_assigned': '현장이 배정되었습니다.',
    'manager_detail.site_assign_failed': '현장 배정 실패.',
    'manager_detail.site_unassigned': '현장 배정이 해제되었습니다.',
    'manager_detail.site_unassign_failed': '해제 실패.',
    'manager_detail.revoked': '권한이 해제되었습니다.',
    'manager_detail.revoke_failed': '처리 실패.',
    'manager_detail.save_success': '저장되었습니다.',
    'manager_detail.save_failed': '저장 실패. 다시 시도해주세요.',
    'manager_detail.tab_basic': '기본 정보',
    'manager_detail.tab_site': '사업장 정보',
    'manager_detail.tab_docs': '서류 확인',
    'manager_detail.tab_approval': '승인 정보',
    'manager_detail.tab_sites': '현장 배정',
    'manager_detail.field_business_type': '사업 유형',
    'manager_detail.business_type_individual': '개인',
    'manager_detail.business_type_corporate': '법인',
    'manager_detail.field_company_name': '회사명',
    'manager_detail.field_representative': '대표자명',
    'manager_detail.field_representative_dob': '대표자 생년월일',
    'manager_detail.field_representative_gender': '대표자 성별',
    'manager_detail.field_gender_none': '선택 안 함',
    'manager_detail.field_gender_male': '남성',
    'manager_detail.field_gender_female': '여성',
    'manager_detail.field_gender_other': '기타',
    'manager_detail.field_contact_phone': '연락처 전화번호',
    'manager_detail.field_reg_number': '사업자등록번호',
    'manager_detail.field_contact_address': '사업장 주소',
    'manager_detail.field_province': '성/시 (Province)',
    'manager_detail.field_first_site_name': '첫 번째 현장명',
    'manager_detail.field_first_site_address': '첫 번째 현장 주소',
    'manager_detail.docs_title': '첨부 서류 이미지',
    'manager_detail.doc_reg_cert': '사업자등록증',
    'manager_detail.doc_signature': '서명',
    'manager_detail.doc_profile_picture': '프로필 사진',
    'manager_detail.approval_status_label': '승인 상태',
    'manager_detail.approval_date': '승인일',
    'manager_detail.rejection_reason': '반려 사유',
    'manager_detail.joined': '가입일',
    'manager_detail.verified_phone': '전화번호 (인증)',
    'manager_detail.sites_assigned': '배정된 현장',
    'manager_detail.sites_none': '배정된 현장이 없습니다.',
    'manager_detail.sites_none_hint': '아래에서 현장을 선택해 배정하세요.',
    'manager_detail.site_status_active': '운영 중',
    'manager_detail.site_status_paused': '일시 중지',
    'manager_detail.site_status_completed': '완료',
    'manager_detail.assigned_date': '배정일: ',
    'manager_detail.unassign': '배정 해제',
    'manager_detail.unassigning': '해제 중...',
    'manager_detail.site_add': '현장 추가',
    'manager_detail.site_search_placeholder': '현장명 또는 주소 검색...',
    'manager_detail.site_no_results': '검색 결과가 없거나 모든 현장이 배정되었습니다.',
    'manager_detail.site_no_sites': '등록된 현장이 없습니다.',
    'manager_detail.assign': '배정',
    'manager_detail.assigning': '배정 중...',
    'manager_detail.site_loading': '로딩 중...',

    'notifications.title': '알림 관리',
    'notifications.subtitle': '근로자 및 관리자에게 푸시 알림과 SMS를 발송합니다.',
    'notifications.flash_sent': '알림이 발송되었습니다.',
    'notifications.flash_scheduled': '알림이 예약되었습니다.',
    'notifications.flash_cancelled': '예약이 취소되었습니다.',
    'notifications.flash_error': '오류가 발생했습니다.',
    'notifications.form_title': '✍️ 알림 작성',
    'notifications.field_title': '알림 제목 *',
    'notifications.field_title_placeholder': '예: 새 일자리 공고가 등록되었습니다',
    'notifications.field_body': '알림 내용 *',
    'notifications.field_body_placeholder': '전송할 메시지 내용을 입력하세요 (최대 300자)',
    'notifications.field_channel': '발송 채널 *',
    'notifications.sms_warning': '⚠️ SMS는 등록된 전화번호로 발송됩니다. 개발 환경에서는 콘솔에 로깅됩니다.',
    'notifications.field_target': '수신 대상',
    'notifications.target_role': '역할별 전체',
    'notifications.target_users': '개별 회원 선택',
    'notifications.field_target_role': '대상 역할',
    'notifications.role_worker_all': '근로자 전체',
    'notifications.role_manager_all': '현장소장 전체',
    'notifications.field_user_search': '회원 검색 및 선택',
    'notifications.user_search_placeholder': '이름 또는 전화번호로 검색...',
    'notifications.role_worker': '근로자',
    'notifications.role_manager': '소장',
    'notifications.role_all': '전체',
    'notifications.selected_users': '선택된 회원 ({n}명)',
    'notifications.field_send_time': '발송 시간',
    'notifications.send_now': '즉시 발송',
    'notifications.send_schedule': '예약 발송',
    'notifications.field_schedule_at': '예약 일시',
    'notifications.submit_now': '🚀 즉시 발송',
    'notifications.submit_schedule': '📅 예약 등록',
    'notifications.submitting': '발송 중...',
    'notifications.alert_no_channel': '발송 채널을 선택해주세요',
    'notifications.alert_no_users': '대상 사용자가 없습니다',
    'notifications.push_label': '푸시 알림 (FCM)',
    'notifications.push_desc': '앱을 설치한 사용자에게 전송. FCM 토큰이 등록된 기기로 전달됩니다.',
    'notifications.sms_label': 'SMS 문자',
    'notifications.sms_desc': '전화번호가 등록된 모든 사용자에게 전송. 앱 미설치 사용자에게도 도달합니다.',
    'notifications.channel_guide': '📊 채널 안내',
    'notifications.scheduled_title': '📅 예약된 알림',
    'notifications.no_scheduled': '예약된 알림이 없습니다',
    'notifications.status_pending': '대기',
    'notifications.status_sent': '발송됨',
    'notifications.status_cancelled': '취소됨',
    'notifications.status_failed': '실패',
    'notifications.target_worker_suffix': '근로자',
    'notifications.target_manager_suffix': '소장',
    'notifications.cancel_schedule': '취소',
    'notifications.confirm_cancel_schedule': '예약을 취소하시겠습니까?',

    'promote_worker.title': '관리자 직접 지정',
    'promote_worker.subtitle': '근로자를 검색하여 관리자로 즉시 지정합니다.',
    'promote_worker.warning': '⚠️ 직접 지정은 실제 검증이 완료된 경우에만 사용하세요.',
    'promote_worker.warning_body': '지정 즉시 해당 근로자는 관리자 권한이 활성화됩니다.',
    'promote_worker.section1': '1. 근로자 검색',
    'promote_worker.search_placeholder': '이름 또는 전화번호 검색',
    'promote_worker.search_btn': '검색',
    'promote_worker.searching': '검색 중...',
    'promote_worker.loading_detail': '근로자 정보 불러오는 중...',
    'promote_worker.id_verified': '신분증 인증',
    'promote_worker.id_unverified': '미인증',
    'promote_worker.select_arrow': '선택 →',
    'promote_worker.reselect': '다시 선택',
    'promote_worker.section2': '2. 관리자 정보 입력',
    'promote_worker.field_business_type': '사업자 유형',
    'promote_worker.business_individual': '개인',
    'promote_worker.business_corporate': '법인',
    'promote_worker.field_representative': '담당자명',
    'promote_worker.field_company': '회사명',
    'promote_worker.field_dob': '생년월일',
    'promote_worker.field_gender': '성별',
    'promote_worker.gender_none': '선택 안 함',
    'promote_worker.gender_male': '남성',
    'promote_worker.gender_female': '여성',
    'promote_worker.gender_other': '기타',
    'promote_worker.field_reg_number': '사업자등록번호',
    'promote_worker.field_phone': '연락처',
    'promote_worker.field_address': '사업장 주소',
    'promote_worker.field_region': '지역',
    'promote_worker.field_first_site': '첫 번째 현장명',
    'promote_worker.field_first_site_address': '현장 주소',
    'promote_worker.submit': '관리자로 지정하기',
    'promote_worker.submitting': '처리 중...',
    'promote_worker.success_title': '관리자 지정 완료',
    'promote_worker.success_body': '님이 관리자로 지정되었습니다.',
    'promote_worker.view_managers': '관리자 목록 보기',
    'promote_worker.representative_required': '담당자명은 필수입니다.',
    'promote_worker.search_failed': '검색 실패',
    'promote_worker.no_results': '검색 결과가 없습니다. 이름 또는 전화번호를 확인해 주세요.',
    'promote_worker.load_failed': '근로자 정보를 불러오지 못했습니다.',
    'promote_worker.no_user_id': '이 근로자의 user_id를 찾을 수 없습니다.',
    'promote_worker.submit_failed': '지정에 실패했습니다.',
  },
  vi: {
    'settings.title': 'Cài đặt',
    'settings.language.title': 'Cài đặt ngôn ngữ',
    'settings.language.subtitle': 'Chọn ngôn ngữ hiển thị của bảng quản trị',
    'settings.language.ko': '한국어',
    'settings.language.vi': 'Tiếng Việt',
    'settings.language.en': 'English',
    'settings.language.current_suffix': '(Hiện tại)',

    'nav.dashboard': '📊 Bảng điều khiển',
    'nav.managers': '👔 Duyệt quản lý',
    'nav.managers_promote': '➕ Chỉ định quản lý',
    'nav.workers': '👷 Quản lý công nhân',
    'nav.jobs': '🏗️ Quản lý việc làm',
    'nav.sites': '🏗️ Quản lý công trường',
    'nav.companies': '🏢 Quản lý công ty',
    'nav.notifications': '🔔 Gửi thông báo',
    'nav.admin_users': '🔑 Tài khoản admin',
    'nav.test_accounts': '🧪 Tài khoản thử nghiệm',
    'nav.settings': '⚙️ Cài đặt',

    'layout.change_password': '🔒 Đổi mật khẩu',
    'layout.logout': 'Đăng xuất',
    'layout.role.super_admin': 'Siêu quản trị',
    'layout.role.admin': 'Quản trị',
    'layout.role.viewer': 'Xem',

    'layout.pw_modal.title': 'Đổi mật khẩu',
    'layout.pw_modal.current': 'Mật khẩu hiện tại',
    'layout.pw_modal.new': 'Mật khẩu mới (tối thiểu 8 ký tự)',
    'layout.pw_modal.confirm': 'Xác nhận mật khẩu mới',
    'layout.pw_modal.cancel': 'Hủy',
    'layout.pw_modal.submit': 'Đổi',
    'layout.pw_modal.submitting': 'Đang đổi...',
    'layout.pw_modal.success': 'Mật khẩu đã được thay đổi',
    'layout.pw_modal.ok': 'OK',
    'layout.pw_modal.error_mismatch': 'Mật khẩu mới không khớp',
    'layout.pw_modal.error_min_length': 'Mật khẩu phải có ít nhất 8 ký tự',
    'layout.pw_modal.error_failed': 'Đổi mật khẩu thất bại',

    'common.loading': 'Đang tải...',
    'common.demo_data': 'Dữ liệu demo',
    'common.demo_suffix': '— Dữ liệu thực sẽ hiển thị sau khi kết nối API',
    'common.save': 'Lưu',
    'common.saving': 'Đang lưu...',
    'common.cancel': 'Hủy',
    'common.edit': 'Sửa',
    'common.delete': 'Xóa',
    'common.detail': 'Chi tiết',
    'common.detail_arrow': 'Chi tiết →',
    'common.back_to_list': '← Về danh sách',
    'common.deactivate': 'Xóa',
    'common.deactivated': 'Đã xóa',
    'common.saved': 'Đã cập nhật',
    'common.deleted': 'Đã xóa',
    'common.not_registered': 'Chưa đăng ký',
    'common.registered': '✓ Đã đăng ký',
    'common.search': 'Tìm kiếm',
    'common.searching': 'Đang tìm...',
    'common.total_count': 'Tổng {n}',
    'common.processing': 'Đang xử lý...',
    'common.save_failed': 'Lưu thất bại',
    'common.delete_failed': 'Xóa thất bại',
    'common.none': '-',
    'common.created_at': 'Ngày tạo',
    'common.updated_at': 'Ngày cập nhật',
    'common.per_page': 'mỗi trang',

    'managers.title': 'Duyệt quản lý',
    'managers.tab_pending': 'Chờ duyệt',
    'managers.tab_approved': 'Đã duyệt',
    'managers.tab_rejected': 'Từ chối',
    'managers.col_name': 'Tên công nhân',
    'managers.col_phone': 'Điện thoại',
    'managers.col_site': 'Công trường',
    'managers.col_status': 'Trạng thái',
    'managers.col_joined': 'Ngày tham gia',
    'managers.status_pending': 'Chờ duyệt',
    'managers.status_approved': 'Đã duyệt',
    'managers.status_rejected': 'Từ chối',
    'managers.revoke': 'Thu hồi quyền',
    'managers.detail_arrow': 'Chi tiết →',
    'managers.empty': 'Không có quản lý phù hợp',
    'managers.total': 'Tổng {n}',
    'managers.flash_approved': '✅ Đã duyệt quản lý.',
    'managers.flash_rejected': '❌ Đã từ chối đơn đăng ký quản lý.',
    'managers.confirm_revoke': 'Bạn có chắc muốn thu hồi quyền quản lý này?',

    'dashboard.title': 'Bảng điều khiển',
    'dashboard.pending_managers': 'Quản lý chờ duyệt',
    'dashboard.total_workers': 'Tổng công nhân',
    'dashboard.active_sites': 'Công trường hoạt động',
    'dashboard.open_jobs': 'Việc làm đang tuyển',
    'dashboard.table_pending_managers': 'Quản lý chờ duyệt',
    'dashboard.view_all': 'Xem tất cả →',
    'dashboard.col_name': 'Tên',
    'dashboard.col_phone': 'Điện thoại',
    'dashboard.col_joined': 'Ngày tham gia',
    'dashboard.no_pending': 'Không có quản lý chờ duyệt',
    'dashboard.detail_arrow': 'Chi tiết →',

    'workers.title': 'Quản lý công nhân',
    'workers.register': '+ Đăng ký công nhân',
    'workers.search_placeholder': 'Tìm theo tên hoặc số điện thoại...',
    'jobs.search_placeholder': 'Tìm tiêu đề hoặc công trường...',
    'sites.search_placeholder': 'Tìm tên, địa chỉ hoặc công ty...',
    'companies.search_placeholder': 'Tìm tên công ty...',
    'workers.col_name': 'Tên',
    'workers.col_phone': 'Điện thoại',
    'workers.col_region': 'Khu vực',
    'workers.col_id_verified': 'Xác minh CMND',
    'workers.col_role': 'Vai trò',
    'workers.col_joined': 'Ngày tham gia',
    'workers.id_verified': 'Đã xác minh',
    'workers.id_unverified': 'Chưa xác minh',
    'workers.role_manager': 'Quản lý',
    'workers.role_worker': 'Công nhân',
    'workers.empty': 'Không có công nhân',
    'workers.total': 'Tổng {n} người',
    'workers.registered': 'Đã đăng ký công nhân',
    'workers.confirm_deactivate': 'Bạn có muốn xóa công nhân này? Thao tác này không thể hoàn tác.',
    'workers.modal.title': 'Đăng ký công nhân',
    'workers.modal.phone_label': 'Số điện thoại *',
    'workers.modal.name_label': 'Tên *',
    'workers.modal.register': 'Đăng ký',
    'workers.modal.registering': 'Đang đăng ký...',
    'workers.modal.register_failed': 'Đăng ký thất bại',

    'sites.title': 'Quản lý công trường',
    'sites.new': '+ Công trường mới',
    'sites.empty': 'Chưa có công trường nào',
    'sites.first_register': '+ Đăng ký công trường đầu tiên',
    'sites.total': 'Tổng {n} công trường',
    'sites.col_name': 'Tên công trường',
    'sites.col_company': 'Công ty',
    'sites.col_address': 'Địa chỉ',
    'sites.col_status': 'Trạng thái',
    'sites.col_manager': 'Quản lý công trường',
    'sites.col_job_count': 'Số việc làm',
    'sites.col_registered': 'Ngày đăng ký',
    'sites.status_active': 'Đang hoạt động',
    'sites.status_completed': 'Hoàn thành',
    'sites.status_paused': 'Tạm dừng',
    'sites.registered': 'Đã đăng ký công trường',
    'sites.confirm_delete': 'Bạn có muốn xóa công trường này? Các việc làm liên kết cũng sẽ bị xóa.',
    'sites.modal.edit_title': 'Sửa công trường',
    'sites.modal.create_title': 'Đăng ký công trường mới',
    'sites.modal.company': 'Công ty',
    'sites.modal.company_none': 'Không chọn',
    'sites.modal.manager': 'Quản lý công trường *',
    'sites.modal.manager_placeholder': 'Tìm theo tên hoặc số điện thoại...',
    'sites.modal.manager_required': 'Vui lòng chọn quản lý công trường.',
    'sites.modal.site_name': 'Tên công trường *',
    'sites.modal.address': 'Địa chỉ *',
    'sites.modal.province': 'Tỉnh/Vùng *',
    'sites.modal.district': 'Quận/Huyện',
    'sites.modal.site_type': 'Loại công trường',
    'sites.modal.site_type_placeholder': 'VD: Chung cư, Thương mại, Đường...',
    'sites.modal.status': 'Trạng thái',
    'sites.modal.save_edit': 'Cập nhật',
    'sites.modal.save_create': 'Đăng ký',
    'sites.modal.saving': 'Đang lưu...',
    'sites.detail.back': '← Về danh sách công trường',
    'sites.detail.type': 'Loại',
    'sites.detail.company': 'Công ty',
    'sites.detail.manager': 'Quản lý công trường',
    'sites.detail.contact': 'Liên hệ',
    'sites.detail.company_contact_title': 'Thông tin liên hệ công ty',
    'sites.detail.contact_person': 'Người liên hệ',
    'sites.detail.phone': 'Điện thoại',
    'sites.detail.email': 'Email',
    'sites.detail.jobs_title': 'Danh sách việc làm',
    'sites.detail.no_jobs': 'Chưa có việc làm nào',
    'sites.detail.col_title': 'Tiêu đề',
    'sites.detail.col_status': 'Trạng thái',
    'sites.detail.col_work_date': 'Ngày làm',
    'sites.detail.col_wage': 'Lương ngày',
    'sites.detail.col_applicants': 'Ứng viên',
    'sites.detail.col_hired': 'Tuyển được',
    'sites.detail.job_status_open': 'Đang tuyển',
    'sites.detail.job_status_closed': 'Đã đóng',
    'sites.detail.job_status_draft': 'Nháp',
    'sites.detail.count_suffix': 'người',
    'sites.load_error': 'Không thể tải thông tin công trường',

    'jobs.title': 'Quản lý việc làm',
    'jobs.new': '+ Việc làm mới',
    'jobs.empty': 'Không có việc làm',
    'jobs.first_register': '+ Đăng việc làm đầu tiên',
    'jobs.total': 'Tổng {n} việc làm',
    'jobs.tab_all': 'Tất cả',
    'jobs.tab_open': 'Đang tuyển',
    'jobs.tab_filled': 'Đã đóng',
    'jobs.tab_cancelled': 'Đã hủy',
    'jobs.col_title': 'Tiêu đề',
    'jobs.col_site': 'Công trường',
    'jobs.col_work_date': 'Ngày làm',
    'jobs.col_wage': 'Lương ngày',
    'jobs.col_slots': 'Số lượng',
    'jobs.col_status': 'Trạng thái',
    'jobs.status_open': 'Đang tuyển',
    'jobs.status_filled': 'Đã đóng',
    'jobs.status_cancelled': 'Đã hủy',
    'jobs.flash_created': '✅ Đã đăng việc làm.',
    'jobs.flash_updated': '✅ Đã cập nhật.',
    'jobs.flash_deleted': '🗑️ Đã hủy.',
    'jobs.confirm_cancel': 'Bạn có muốn hủy việc làm này?',
    'jobs.slots_suffix': 'người',
    'jobs.form.back': '← Danh sách',
    'jobs.form.title_new': 'Đăng ký việc làm',
    'jobs.form.title_edit': 'Chỉnh sửa việc làm',
    'jobs.form.field_site': 'Công trường *',
    'jobs.form.site_placeholder': 'Chọn...',
    'jobs.form.field_title': 'Tiêu đề *',
    'jobs.form.field_trade': 'Ngành nghề',
    'jobs.form.trade_none': 'Không chọn',
    'jobs.form.field_work_date': 'Ngày làm việc *',
    'jobs.form.field_start_time': 'Giờ bắt đầu',
    'jobs.form.field_end_time': 'Giờ kết thúc',
    'jobs.form.field_daily_wage': 'Lương ngày (₫) *',
    'jobs.form.field_slots_total': 'Số lượng tuyển *',
    'jobs.form.field_status': 'Trạng thái',
    'jobs.form.field_description': 'Mô tả',
    'jobs.form.save_new': 'Đăng ký',
    'jobs.form.save_edit': 'Lưu thay đổi',
    'jobs.form.saving': 'Đang lưu...',
    'jobs.form.save_failed': 'Lưu thất bại',
    'jobs.form.loading': 'Đang tải...',

    'companies.title': 'Quản lý công ty',
    'companies.subtitle': 'Quản lý thông tin công ty xây dựng liên kết với công trường',
    'companies.new': '+ Công ty mới',
    'companies.empty': 'Chưa có công ty nào',
    'companies.first_register': '+ Đăng ký công ty đầu tiên',
    'companies.total': 'Tổng {n} công ty',
    'companies.col_name': 'Tên công ty',
    'companies.col_reg_no': 'Mã số thuế',
    'companies.col_contact': 'Người liên hệ',
    'companies.col_phone': 'Điện thoại',
    'companies.col_sites': 'Công trường',
    'companies.col_signature': 'Chữ ký',
    'companies.col_registered': 'Ngày đăng ký',
    'companies.sites_suffix': '',
    'companies.registered': 'Đã đăng ký công ty',
    'companies.confirm_delete': 'Bạn có muốn xóa công ty này?',
    'companies.modal.edit_title': 'Sửa công ty',
    'companies.modal.create_title': 'Đăng ký công ty mới',
    'companies.modal.name': 'Tên công ty *',
    'companies.modal.reg_no': 'Mã số thuế',
    'companies.modal.contact_name': 'Tên người liên hệ',
    'companies.modal.contact_phone': 'Điện thoại người liên hệ',
    'companies.modal.contact_email': 'Email người liên hệ',
    'companies.modal.save_edit': 'Cập nhật',
    'companies.modal.save_create': 'Đăng ký',
    'companies.modal.saving': 'Đang lưu...',
    'companies.detail.back': '← Về danh sách công ty',
    'companies.detail.reg_no_label': 'Mã số thuế: ',
    'companies.detail.contact': 'Người liên hệ',
    'companies.detail.phone': 'Điện thoại',
    'companies.detail.email': 'Email',
    'companies.detail.linked_sites': 'Công trường liên kết',
    'companies.detail.linked_sites_suffix': '',
    'companies.detail.signature': 'Chữ ký / Con dấu',
    'companies.detail.signature_alt': 'Chữ ký công ty',
    'companies.detail.no_signature': 'Chưa đăng ký chữ ký',
    'companies.detail.reg_cert': 'Giấy phép kinh doanh',
    'companies.detail.view_reg_cert': '📄 Xem giấy phép kinh doanh',
    'companies.load_error': 'Không thể tải thông tin công ty',
    'companies.seal.upload': 'Tải ảnh lên',
    'companies.seal.change': 'Thay ảnh',
    'companies.seal.drop_hint': 'Nhấn để tải ảnh lên',
    'companies.seal.uploaded': 'Đã đăng ký chữ ký/con dấu',
    'companies.seal.upload_failed': 'Tải lên thất bại. Vui lòng thử lại.',
    'companies.seal.deleted': 'Đã xóa chữ ký/con dấu',
    'companies.seal.confirm_delete': 'Bạn có muốn xóa ảnh chữ ký/con dấu?',

    'test_accounts.title': 'Quản lý tài khoản thử nghiệm',
    'test_accounts.subtitle': 'Quản lý số điện thoại thử nghiệm có thể đăng nhập bằng OTP cố định (000000)',
    'test_accounts.add': '+ Thêm tài khoản thử nghiệm',
    'test_accounts.empty': 'Chưa có tài khoản thử nghiệm',
    'test_accounts.otp_hint': 'Số điện thoại đăng ký làm tài khoản thử nghiệm có thể đăng nhập bằng mã "000000".',
    'test_accounts.col_phone': 'Số điện thoại',
    'test_accounts.col_name': 'Tên',
    'test_accounts.col_role': 'Vai trò',
    'test_accounts.col_status': 'Trạng thái',
    'test_accounts.col_created': 'Ngày tạo',
    'test_accounts.role_worker': 'Công nhân',
    'test_accounts.role_manager': 'Quản lý',
    'test_accounts.confirm_delete': 'Bạn có muốn xóa tài khoản thử nghiệm này?',
    'test_accounts.deleted': 'Đã xóa tài khoản thử nghiệm',
    'test_accounts.created': 'Đã thêm tài khoản thử nghiệm',
    'test_accounts.error_phone_required': 'Vui lòng nhập số điện thoại',
    'test_accounts.error_create_failed': 'Thêm thất bại',
    'test_accounts.add_modal.title': 'Thêm tài khoản thử nghiệm',
    'test_accounts.add_modal.phone': 'Số điện thoại',
    'test_accounts.add_modal.name': 'Tên',
    'test_accounts.add_modal.name_placeholder': 'VD: Công nhân thử nghiệm',
    'test_accounts.add_modal.role': 'Vai trò',
    'test_accounts.add_modal.submit': 'Thêm',

    'login.brand': '가다 VN',
    'login.error_credentials': 'Tên đăng nhập hoặc mật khẩu không đúng.',
    'login.logout_success': 'Đã đăng xuất.',
    'login.username': 'Tên đăng nhập',
    'login.password': 'Mật khẩu',
    'login.submit': 'Đăng nhập',
    'login.submitting': 'Đang đăng nhập...',

    'admin_users.title': 'Quản lý tài khoản admin',
    'admin_users.subtitle': 'Cấu hình quyền truy cập theo menu và mời tài khoản qua email',
    'admin_users.invite': '+ Mời tài khoản',
    'admin_users.col_email': 'Email / Tên',
    'admin_users.col_role': 'Cấp độ',
    'admin_users.col_permissions': 'Quyền menu',
    'admin_users.col_status': 'Trạng thái',
    'admin_users.col_last_login': 'Đăng nhập cuối',
    'admin_users.me': 'Tôi',
    'admin_users.status_active': 'Hoạt động',
    'admin_users.status_invited': 'Chờ xác nhận',
    'admin_users.status_disabled': 'Vô hiệu',
    'admin_users.role_super_admin': 'Siêu quản trị',
    'admin_users.role_admin': 'Quản trị',
    'admin_users.role_viewer': 'Xem',
    'admin_users.action_edit_permissions': 'Chỉnh quyền',
    'admin_users.action_reset_password': 'Đặt lại mật khẩu',
    'admin_users.action_resend': 'Gửi lại',
    'admin_users.action_disable': 'Vô hiệu hóa',
    'admin_users.confirm_disable': 'Bạn có muốn vô hiệu hóa tài khoản này?',
    'admin_users.disabled': 'Đã vô hiệu hóa',
    'admin_users.action_delete': 'Xóa',
    'admin_users.confirm_delete': 'Bạn có chắc muốn xóa vĩnh viễn tài khoản này? Hành động này không thể hoàn tác.',
    'admin_users.deleted': 'Đã xóa tài khoản',
    'admin_users.invite_issued': 'Đã cấp liên kết mời',
    'admin_users.permissions_saved': 'Đã lưu quyền',
    'admin_users.password_changed': 'Đã thay đổi mật khẩu',
    'admin_users.invite_modal.title': 'Mời tài khoản admin',
    'admin_users.invite_modal.invite_done': 'Đã cấp liên kết mời',
    'admin_users.invite_modal.invite_instruction': 'Hãy gửi liên kết mời cho',
    'admin_users.invite_modal.invite_link_label': 'Liên kết mời (hiệu lực 7 ngày)',
    'admin_users.invite_modal.copy': 'Sao chép',
    'admin_users.invite_modal.close': 'Đóng',
    'admin_users.invite_modal.email': 'Email *',
    'admin_users.invite_modal.name': 'Tên',
    'admin_users.invite_modal.name_placeholder': 'Nguyễn Văn A',
    'admin_users.invite_modal.role': 'Cấp độ *',
    'admin_users.invite_modal.permissions': 'Quyền truy cập menu',
    'admin_users.invite_modal.submit': 'Cấp liên kết mời',
    'admin_users.invite_modal.submitting': 'Đang xử lý...',
    'admin_users.invite_modal.invite_failed': 'Mời thất bại',
    'admin_users.invite_modal.email_sent': 'Email mời đã được gửi',
    'admin_users.invite_modal.email_not_sent': 'Gửi email thất bại — vui lòng sao chép và gửi liên kết bên dưới',
    'admin_users.permissions_modal.title': 'Chỉnh sửa quyền',
    'admin_users.permissions_modal.role': 'Cấp độ',
    'admin_users.permissions_modal.permissions': 'Quyền truy cập menu',
    'admin_users.permissions_modal.save': 'Lưu',
    'admin_users.permissions_modal.saving': 'Đang lưu...',
    'admin_users.permissions_modal.save_failed': 'Lưu thất bại',
    'admin_users.reset_pw_modal.title': 'Đặt lại mật khẩu',
    'admin_users.reset_pw_modal.new_password': 'Mật khẩu mới',
    'admin_users.reset_pw_modal.new_password_placeholder': 'Tối thiểu 8 ký tự',
    'admin_users.reset_pw_modal.confirm': 'Xác nhận mật khẩu',
    'admin_users.reset_pw_modal.submit': 'Đặt lại mật khẩu',
    'admin_users.reset_pw_modal.submitting': 'Đang thay đổi...',
    'admin_users.reset_pw_modal.error_mismatch': 'Mật khẩu không khớp',
    'admin_users.reset_pw_modal.error_min_length': 'Mật khẩu phải có ít nhất 8 ký tự',
    'admin_users.reset_pw_modal.change_failed': 'Thay đổi thất bại',
    'admin_users.menu.dashboard': '📊 Bảng điều khiển',
    'admin_users.menu.managers': '👔 Duyệt quản lý',
    'admin_users.menu.workers': '👷 Quản lý công nhân',
    'admin_users.menu.jobs': '🏗️ Quản lý việc làm',
    'admin_users.menu.sites': '🏢 Quản lý công trường',
    'admin_users.menu.notifications': '🔔 Gửi thông báo',
    'admin_users.menu.admin_users': '🔑 Tài khoản admin',

    'worker_detail.not_found': 'Không tìm thấy công nhân',
    'worker_detail.manager_badge': 'Quản lý',
    'worker_detail.id_verified': 'Đã xác minh CMND',
    'worker_detail.id_unverified': 'Chưa xác minh',
    'worker_detail.id_verified_badge': 'Đã xác minh',
    'worker_detail.id_unverified_badge': 'Chưa xác minh',
    'worker_detail.profile_complete': 'Hồ sơ hoàn chỉnh',
    'worker_detail.id_verified_check': 'Xác minh CMND',
    'worker_detail.confirm_deactivate': 'Bạn có muốn xóa công nhân này? Thao tác này không thể hoàn tác.',
    'worker_detail.deactivate_failed': 'Xóa thất bại',
    'worker_detail.save_success': 'Đã lưu.',
    'worker_detail.save_failed': 'Lưu thất bại. Vui lòng thử lại.',
    'worker_detail.skills_saved': 'Đã lưu kỹ năng nghề.',
    'worker_detail.tab_basic': 'Thông tin cơ bản',
    'worker_detail.tab_docs': 'CMND / Giấy tờ',
    'worker_detail.tab_bank': 'Ngân hàng / Thanh toán',
    'worker_detail.tab_trades': 'Nghề / Kỹ năng',
    'worker_detail.tab_manager': 'Quản lý',
    'worker_detail.tab_misc': 'Khác',
    'worker_detail.tab_contracts': 'Hợp đồng',
    'worker_detail.contracts_loading': 'Đang tải...',
    'worker_detail.contracts_empty': 'Không có hợp đồng nào.',
    'worker_detail.contracts_error': 'Không thể tải hợp đồng.',
    'worker_detail.contract_status_pending_worker_sign': 'Chờ người lao động ký',
    'worker_detail.contract_status_pending_manager_sign': 'Chờ nhà thầu ký',
    'worker_detail.contract_status_fully_signed': 'Hoàn tất hợp đồng',
    'worker_detail.contract_status_void': 'Hợp đồng vô hiệu',
    'worker_detail.contract_job_title': 'Việc làm',
    'worker_detail.contract_site': 'Công trường',
    'worker_detail.contract_work_date': 'Ngày làm việc',
    'worker_detail.contract_daily_wage': 'Lương ngày',
    'worker_detail.contract_worker_signed': 'Chữ ký NLĐ',
    'worker_detail.contract_created_at': 'Ngày tạo',
    'worker_detail.field_name': 'Tên',
    'worker_detail.field_dob': 'Ngày sinh',
    'worker_detail.field_gender': 'Giới tính',
    'worker_detail.field_gender_none': 'Không chọn',
    'worker_detail.field_gender_male': 'Nam',
    'worker_detail.field_gender_female': 'Nữ',
    'worker_detail.field_gender_other': 'Khác',
    'worker_detail.field_bio': 'Giới thiệu bản thân',
    'worker_detail.field_trade_id': 'ID nghề chính',
    'worker_detail.field_experience': 'Kinh nghiệm (tháng)',
    'worker_detail.field_id_number': 'Số CMND / Căn cước',
    'worker_detail.field_verified_at': 'Ngày xác minh',
    'worker_detail.unverified_date': 'Chưa xác minh',
    'worker_detail.attachments_title': 'Hình ảnh đính kèm',
    'worker_detail.field_id_front': 'Mặt trước CMND',
    'worker_detail.field_id_back': 'Mặt sau CMND',
    'worker_detail.field_bank_book': 'Sổ ngân hàng',
    'worker_detail.field_signature': 'Chữ ký',
    'worker_detail.field_bank_name': 'Tên ngân hàng',
    'worker_detail.field_bank_account': 'Số tài khoản',
    'worker_detail.trades_loading': 'Đang tải...',
    'worker_detail.trades_empty': 'Chưa có nghề nào.',
    'worker_detail.trade_select': 'Chọn nghề',
    'worker_detail.experience_years_placeholder': 'Kinh nghiệm (năm)',
    'worker_detail.experience_years_suffix': 'năm',
    'worker_detail.trade_add': '+ Thêm nghề',
    'worker_detail.manager_active': 'Quản lý đang hoạt động',
    'worker_detail.approved_suffix': 'đã duyệt)',
    'worker_detail.field_company': 'Công ty',
    'worker_detail.field_contact_name': 'Người liên hệ',
    'worker_detail.manager_profile_link': 'Xem chi tiết hồ sơ quản lý →',
    'worker_detail.no_manager': 'Công nhân này chưa có quyền quản lý.',
    'worker_detail.promote_link': 'Chỉ định làm quản lý →',
    'worker_detail.field_phone': 'Điện thoại',
    'worker_detail.field_email': 'Email',
    'worker_detail.field_lat': 'Vĩ độ (lat)',
    'worker_detail.field_lng': 'Kinh độ (lng)',
    'worker_detail.terms_accepted': 'Đồng ý điều khoản sử dụng',
    'worker_detail.privacy_accepted': 'Đồng ý chính sách bảo mật',
    'worker_detail.field_joined': 'Ngày tham gia',

    'manager_detail.not_found': 'Không tìm thấy quản lý',
    'manager_detail.status_approved': 'Đã duyệt',
    'manager_detail.status_rejected': 'Từ chối',
    'manager_detail.status_revoked': 'Đã thu hồi',
    'manager_detail.status_pending': 'Chờ duyệt',
    'manager_detail.approve': 'Duyệt',
    'manager_detail.reject': 'Từ chối',
    'manager_detail.revoke': 'Thu hồi quyền',
    'manager_detail.re_approve': 'Xét duyệt lại (Duyệt)',
    'manager_detail.confirm_approve': 'Bạn có muốn duyệt?',
    'manager_detail.confirm_revoke': 'Bạn có muốn thu hồi quyền?',
    'manager_detail.reject_reason_label': 'Lý do từ chối',
    'manager_detail.reject_reason_placeholder': 'Nhập lý do từ chối',
    'manager_detail.reject_confirm': 'Xác nhận từ chối',
    'manager_detail.reject_reason_required': 'Vui lòng nhập lý do từ chối.',
    'manager_detail.site_assigned': 'Đã phân công công trường.',
    'manager_detail.site_assign_failed': 'Phân công thất bại.',
    'manager_detail.site_unassigned': 'Đã hủy phân công.',
    'manager_detail.site_unassign_failed': 'Hủy phân công thất bại.',
    'manager_detail.revoked': 'Đã thu hồi quyền.',
    'manager_detail.revoke_failed': 'Xử lý thất bại.',
    'manager_detail.save_success': 'Đã lưu.',
    'manager_detail.save_failed': 'Lưu thất bại. Vui lòng thử lại.',
    'manager_detail.tab_basic': 'Thông tin cơ bản',
    'manager_detail.tab_site': 'Thông tin doanh nghiệp',
    'manager_detail.tab_docs': 'Xác nhận giấy tờ',
    'manager_detail.tab_approval': 'Thông tin duyệt',
    'manager_detail.tab_sites': 'Phân công công trường',
    'manager_detail.field_business_type': 'Loại hình kinh doanh',
    'manager_detail.business_type_individual': 'Cá nhân',
    'manager_detail.business_type_corporate': 'Doanh nghiệp',
    'manager_detail.field_company_name': 'Tên công ty',
    'manager_detail.field_representative': 'Người đại diện',
    'manager_detail.field_representative_dob': 'Ngày sinh người đại diện',
    'manager_detail.field_representative_gender': 'Giới tính người đại diện',
    'manager_detail.field_gender_none': 'Không chọn',
    'manager_detail.field_gender_male': 'Nam',
    'manager_detail.field_gender_female': 'Nữ',
    'manager_detail.field_gender_other': 'Khác',
    'manager_detail.field_contact_phone': 'Điện thoại liên hệ',
    'manager_detail.field_reg_number': 'Mã số thuế',
    'manager_detail.field_contact_address': 'Địa chỉ doanh nghiệp',
    'manager_detail.field_province': 'Tỉnh/Thành',
    'manager_detail.field_first_site_name': 'Tên công trường đầu tiên',
    'manager_detail.field_first_site_address': 'Địa chỉ công trường đầu tiên',
    'manager_detail.docs_title': 'Hình ảnh giấy tờ đính kèm',
    'manager_detail.doc_reg_cert': 'Giấy phép kinh doanh',
    'manager_detail.doc_signature': 'Chữ ký',
    'manager_detail.doc_profile_picture': 'Ảnh đại diện',
    'manager_detail.approval_status_label': 'Trạng thái duyệt',
    'manager_detail.approval_date': 'Ngày duyệt',
    'manager_detail.rejection_reason': 'Lý do từ chối',
    'manager_detail.joined': 'Ngày tham gia',
    'manager_detail.verified_phone': 'Điện thoại (đã xác minh)',
    'manager_detail.sites_assigned': 'Công trường đã phân công',
    'manager_detail.sites_none': 'Chưa có công trường nào được phân công.',
    'manager_detail.sites_none_hint': 'Chọn công trường bên dưới để phân công.',
    'manager_detail.site_status_active': 'Đang hoạt động',
    'manager_detail.site_status_paused': 'Tạm dừng',
    'manager_detail.site_status_completed': 'Hoàn thành',
    'manager_detail.assigned_date': 'Ngày phân công: ',
    'manager_detail.unassign': 'Hủy phân công',
    'manager_detail.unassigning': 'Đang hủy...',
    'manager_detail.site_add': 'Thêm công trường',
    'manager_detail.site_search_placeholder': 'Tìm theo tên hoặc địa chỉ...',
    'manager_detail.site_no_results': 'Không có kết quả hoặc tất cả đã phân công.',
    'manager_detail.site_no_sites': 'Chưa có công trường nào.',
    'manager_detail.assign': 'Phân công',
    'manager_detail.assigning': 'Đang phân công...',
    'manager_detail.site_loading': 'Đang tải...',

    'notifications.title': 'Quản lý thông báo',
    'notifications.subtitle': 'Gửi thông báo đẩy và SMS đến công nhân và quản lý.',
    'notifications.flash_sent': 'Đã gửi thông báo.',
    'notifications.flash_scheduled': 'Đã đặt lịch thông báo.',
    'notifications.flash_cancelled': 'Đã hủy lịch.',
    'notifications.flash_error': 'Đã xảy ra lỗi.',
    'notifications.form_title': '✍️ Soạn thông báo',
    'notifications.field_title': 'Tiêu đề thông báo *',
    'notifications.field_title_placeholder': 'VD: Có việc làm mới đăng',
    'notifications.field_body': 'Nội dung thông báo *',
    'notifications.field_body_placeholder': 'Nhập nội dung tin nhắn (tối đa 300 ký tự)',
    'notifications.field_channel': 'Kênh gửi *',
    'notifications.sms_warning': '⚠️ SMS sẽ được gửi đến số điện thoại đã đăng ký. Trong môi trường dev sẽ log ra console.',
    'notifications.field_target': 'Đối tượng nhận',
    'notifications.target_role': 'Tất cả theo vai trò',
    'notifications.target_users': 'Chọn thành viên cụ thể',
    'notifications.field_target_role': 'Vai trò nhận',
    'notifications.role_worker_all': 'Tất cả công nhân',
    'notifications.role_manager_all': 'Tất cả quản lý',
    'notifications.field_user_search': 'Tìm và chọn thành viên',
    'notifications.user_search_placeholder': 'Tìm theo tên hoặc số điện thoại...',
    'notifications.role_worker': 'Công nhân',
    'notifications.role_manager': 'Quản lý',
    'notifications.role_all': 'Tất cả',
    'notifications.selected_users': 'Đã chọn ({n} người)',
    'notifications.field_send_time': 'Thời gian gửi',
    'notifications.send_now': 'Gửi ngay',
    'notifications.send_schedule': 'Đặt lịch',
    'notifications.field_schedule_at': 'Thời điểm đặt lịch',
    'notifications.submit_now': '🚀 Gửi ngay',
    'notifications.submit_schedule': '📅 Đặt lịch',
    'notifications.submitting': 'Đang gửi...',
    'notifications.alert_no_channel': 'Vui lòng chọn kênh gửi',
    'notifications.alert_no_users': 'Không có người dùng nào',
    'notifications.push_label': 'Thông báo đẩy (FCM)',
    'notifications.push_desc': 'Gửi đến người dùng đã cài ứng dụng. Gửi qua token FCM.',
    'notifications.sms_label': 'SMS',
    'notifications.sms_desc': 'Gửi đến tất cả người dùng có số điện thoại. Kể cả người chưa cài app.',
    'notifications.channel_guide': '📊 Hướng dẫn kênh',
    'notifications.scheduled_title': '📅 Thông báo đã đặt lịch',
    'notifications.no_scheduled': 'Không có thông báo đặt lịch',
    'notifications.status_pending': 'Chờ',
    'notifications.status_sent': 'Đã gửi',
    'notifications.status_cancelled': 'Đã hủy',
    'notifications.status_failed': 'Thất bại',
    'notifications.target_worker_suffix': 'công nhân',
    'notifications.target_manager_suffix': 'quản lý',
    'notifications.cancel_schedule': 'Hủy',
    'notifications.confirm_cancel_schedule': 'Bạn có muốn hủy lịch này?',

    'promote_worker.title': 'Chỉ định quản lý trực tiếp',
    'promote_worker.subtitle': 'Tìm công nhân và chỉ định làm quản lý ngay lập tức.',
    'promote_worker.warning': '⚠️ Chỉ sử dụng khi đã xác minh thực tế.',
    'promote_worker.warning_body': 'Ngay sau khi chỉ định, công nhân sẽ có quyền quản lý.',
    'promote_worker.section1': '1. Tìm công nhân',
    'promote_worker.search_placeholder': 'Tìm theo tên hoặc số điện thoại',
    'promote_worker.search_btn': 'Tìm kiếm',
    'promote_worker.searching': 'Đang tìm...',
    'promote_worker.loading_detail': 'Đang tải thông tin công nhân...',
    'promote_worker.id_verified': 'Đã xác minh CMND',
    'promote_worker.id_unverified': 'Chưa xác minh',
    'promote_worker.select_arrow': 'Chọn →',
    'promote_worker.reselect': 'Chọn lại',
    'promote_worker.section2': '2. Nhập thông tin quản lý',
    'promote_worker.field_business_type': 'Loại hình kinh doanh',
    'promote_worker.business_individual': 'Cá nhân',
    'promote_worker.business_corporate': 'Doanh nghiệp',
    'promote_worker.field_representative': 'Người đại diện',
    'promote_worker.field_company': 'Tên công ty',
    'promote_worker.field_dob': 'Ngày sinh',
    'promote_worker.field_gender': 'Giới tính',
    'promote_worker.gender_none': 'Không chọn',
    'promote_worker.gender_male': 'Nam',
    'promote_worker.gender_female': 'Nữ',
    'promote_worker.gender_other': 'Khác',
    'promote_worker.field_reg_number': 'Mã số thuế',
    'promote_worker.field_phone': 'Liên hệ',
    'promote_worker.field_address': 'Địa chỉ doanh nghiệp',
    'promote_worker.field_region': 'Khu vực',
    'promote_worker.field_first_site': 'Tên công trường đầu tiên',
    'promote_worker.field_first_site_address': 'Địa chỉ công trường',
    'promote_worker.submit': 'Chỉ định làm quản lý',
    'promote_worker.submitting': 'Đang xử lý...',
    'promote_worker.success_title': 'Đã chỉ định quản lý',
    'promote_worker.success_body': 'đã được chỉ định làm quản lý.',
    'promote_worker.view_managers': 'Xem danh sách quản lý',
    'promote_worker.representative_required': 'Người đại diện là bắt buộc.',
    'promote_worker.search_failed': 'Tìm kiếm thất bại',
    'promote_worker.no_results': 'Không tìm thấy kết quả. Vui lòng kiểm tra tên hoặc số điện thoại.',
    'promote_worker.load_failed': 'Không thể tải thông tin công nhân.',
    'promote_worker.no_user_id': 'Không tìm thấy user_id của công nhân này.',
    'promote_worker.submit_failed': 'Chỉ định thất bại.',
  },
  en: {
    'settings.title': 'Settings',
    'settings.language.title': 'Language Settings',
    'settings.language.subtitle': 'Select the display language for the admin panel',
    'settings.language.ko': '한국어',
    'settings.language.vi': 'Tiếng Việt',
    'settings.language.en': 'English',
    'settings.language.current_suffix': '(Current)',

    'nav.dashboard': '📊 Dashboard',
    'nav.managers': '👔 Manager Approval',
    'nav.managers_promote': '➕ Assign Manager',
    'nav.workers': '👷 Worker Management',
    'nav.jobs': '🏗️ Job Management',
    'nav.sites': '🏗️ Site Management',
    'nav.companies': '🏢 Company Management',
    'nav.notifications': '🔔 Send Notifications',
    'nav.admin_users': '🔑 Admin Accounts',
    'nav.test_accounts': '🧪 Test Accounts',
    'nav.settings': '⚙️ Settings',

    'layout.change_password': '🔒 Change Password',
    'layout.logout': 'Log Out',
    'layout.role.super_admin': 'Super Admin',
    'layout.role.admin': 'Admin',
    'layout.role.viewer': 'Viewer',

    'layout.pw_modal.title': 'Change Password',
    'layout.pw_modal.current': 'Current Password',
    'layout.pw_modal.new': 'New Password (min. 8 characters)',
    'layout.pw_modal.confirm': 'Confirm New Password',
    'layout.pw_modal.cancel': 'Cancel',
    'layout.pw_modal.submit': 'Change',
    'layout.pw_modal.submitting': 'Changing...',
    'layout.pw_modal.success': 'Password changed successfully',
    'layout.pw_modal.ok': 'OK',
    'layout.pw_modal.error_mismatch': 'New passwords do not match',
    'layout.pw_modal.error_min_length': 'Password must be at least 8 characters',
    'layout.pw_modal.error_failed': 'Failed to change password',

    'common.loading': 'Loading...',
    'common.demo_data': 'Demo Data',
    'common.demo_suffix': '— Real data will appear after API connection',
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.detail': 'Detail',
    'common.detail_arrow': 'Detail →',
    'common.back_to_list': '← Back to list',
    'common.deactivate': 'Delete',
    'common.deactivated': 'Deleted',
    'common.saved': 'Saved',
    'common.deleted': 'Deleted',
    'common.not_registered': 'Not registered',
    'common.registered': '✓ Registered',
    'common.search': 'Search',
    'common.searching': 'Searching...',
    'common.total_count': 'Total {n}',
    'common.processing': 'Processing...',
    'common.save_failed': 'Save failed',
    'common.delete_failed': 'Delete failed',
    'common.none': '-',
    'common.created_at': 'Created',
    'common.updated_at': 'Updated',
    'common.per_page': 'per page',

    'managers.title': 'Manager Approval',
    'managers.tab_pending': 'Pending',
    'managers.tab_approved': 'Approved',
    'managers.tab_rejected': 'Rejected',
    'managers.col_name': 'Worker Name',
    'managers.col_phone': 'Phone',
    'managers.col_site': 'Site',
    'managers.col_status': 'Status',
    'managers.col_joined': 'Joined',
    'managers.status_pending': 'Pending',
    'managers.status_approved': 'Approved',
    'managers.status_rejected': 'Rejected',
    'managers.revoke': 'Revoke',
    'managers.detail_arrow': 'Detail →',
    'managers.empty': 'No managers found',
    'managers.total': 'Total {n}',
    'managers.flash_approved': '✅ Manager approved.',
    'managers.flash_rejected': '❌ Manager application rejected.',
    'managers.confirm_revoke': 'Are you sure you want to revoke this manager\'s access?',

    'dashboard.title': 'Dashboard',
    'dashboard.pending_managers': 'Pending Managers',
    'dashboard.total_workers': 'Total Workers',
    'dashboard.active_sites': 'Active Sites',
    'dashboard.open_jobs': 'Open Jobs',
    'dashboard.table_pending_managers': 'Pending Manager Approvals',
    'dashboard.view_all': 'View All →',
    'dashboard.col_name': 'Name',
    'dashboard.col_phone': 'Phone',
    'dashboard.col_joined': 'Joined',
    'dashboard.no_pending': 'No pending managers',
    'dashboard.detail_arrow': 'Detail →',

    'workers.title': 'Worker Management',
    'workers.register': '+ Register Worker',
    'workers.search_placeholder': 'Search by name or phone...',
    'jobs.search_placeholder': 'Search title or site name...',
    'sites.search_placeholder': 'Search name, address or company...',
    'companies.search_placeholder': 'Search company name...',
    'workers.col_name': 'Name',
    'workers.col_phone': 'Phone',
    'workers.col_region': 'Region',
    'workers.col_id_verified': 'ID Verified',
    'workers.col_role': 'Role',
    'workers.col_joined': 'Joined',
    'workers.id_verified': 'Verified',
    'workers.id_unverified': 'Unverified',
    'workers.role_manager': 'Manager',
    'workers.role_worker': 'Worker',
    'workers.empty': 'No workers found',
    'workers.total': 'Total {n}',
    'workers.registered': 'Worker registered',
    'workers.confirm_deactivate': 'Delete this worker? This action cannot be undone.',
    'workers.modal.title': 'Register Worker',
    'workers.modal.phone_label': 'Phone *',
    'workers.modal.name_label': 'Name *',
    'workers.modal.register': 'Register',
    'workers.modal.registering': 'Registering...',
    'workers.modal.register_failed': 'Registration failed',

    'sites.title': 'Site Management',
    'sites.new': '+ New Site',
    'sites.empty': 'No sites registered',
    'sites.first_register': '+ Register First Site',
    'sites.total': 'Total {n} sites',
    'sites.col_name': 'Site Name',
    'sites.col_company': 'Company',
    'sites.col_address': 'Address',
    'sites.col_status': 'Status',
    'sites.col_manager': 'Site Manager',
    'sites.col_job_count': 'Jobs',
    'sites.col_registered': 'Registered',
    'sites.status_active': 'Active',
    'sites.status_completed': 'Completed',
    'sites.status_paused': 'Paused',
    'sites.registered': 'Site registered',
    'sites.confirm_delete': 'Delete this site? Associated jobs will also be deleted.',
    'sites.modal.edit_title': 'Edit Site',
    'sites.modal.create_title': 'Register New Site',
    'sites.modal.company': 'Company',
    'sites.modal.company_none': 'None',
    'sites.modal.manager': 'Site Manager *',
    'sites.modal.manager_placeholder': 'Search by name or phone...',
    'sites.modal.manager_required': 'Please select a site manager.',
    'sites.modal.site_name': 'Site Name *',
    'sites.modal.address': 'Address *',
    'sites.modal.province': 'Province *',
    'sites.modal.district': 'District',
    'sites.modal.site_type': 'Site Type',
    'sites.modal.site_type_placeholder': 'e.g. Apartment, Commercial, Road...',
    'sites.modal.status': 'Status',
    'sites.modal.save_edit': 'Save Changes',
    'sites.modal.save_create': 'Register',
    'sites.modal.saving': 'Saving...',
    'sites.detail.back': '← Back to Sites',
    'sites.detail.type': 'Type',
    'sites.detail.company': 'Company',
    'sites.detail.manager': 'Site Manager',
    'sites.detail.contact': 'Contact',
    'sites.detail.company_contact_title': 'Company Contact Info',
    'sites.detail.contact_person': 'Contact Person',
    'sites.detail.phone': 'Phone',
    'sites.detail.email': 'Email',
    'sites.detail.jobs_title': 'Job Listings',
    'sites.detail.no_jobs': 'No jobs registered',
    'sites.detail.col_title': 'Title',
    'sites.detail.col_status': 'Status',
    'sites.detail.col_work_date': 'Work Date',
    'sites.detail.col_wage': 'Daily Wage',
    'sites.detail.col_applicants': 'Applicants',
    'sites.detail.col_hired': 'Hired',
    'sites.detail.job_status_open': 'Open',
    'sites.detail.job_status_closed': 'Closed',
    'sites.detail.job_status_draft': 'Draft',
    'sites.detail.count_suffix': '',
    'sites.load_error': 'Failed to load site info',

    'jobs.title': 'Job Management',
    'jobs.new': '+ New Job',
    'jobs.empty': 'No jobs found',
    'jobs.first_register': '+ Register First Job',
    'jobs.total': 'Total {n}',
    'jobs.tab_all': 'All',
    'jobs.tab_open': 'Open',
    'jobs.tab_filled': 'Filled',
    'jobs.tab_cancelled': 'Cancelled',
    'jobs.col_title': 'Title',
    'jobs.col_site': 'Site',
    'jobs.col_work_date': 'Work Date',
    'jobs.col_wage': 'Daily Wage',
    'jobs.col_slots': 'Slots',
    'jobs.col_status': 'Status',
    'jobs.status_open': 'Open',
    'jobs.status_filled': 'Filled',
    'jobs.status_cancelled': 'Cancelled',
    'jobs.flash_created': '✅ Job registered.',
    'jobs.flash_updated': '✅ Updated.',
    'jobs.flash_deleted': '🗑️ Cancelled.',
    'jobs.confirm_cancel': 'Cancel this job posting?',
    'jobs.slots_suffix': '',
    'jobs.form.back': '← Back to list',
    'jobs.form.title_new': 'New Job',
    'jobs.form.title_edit': 'Edit Job',
    'jobs.form.field_site': 'Site *',
    'jobs.form.site_placeholder': 'Select...',
    'jobs.form.field_title': 'Job Title *',
    'jobs.form.field_trade': 'Trade',
    'jobs.form.trade_none': 'None',
    'jobs.form.field_work_date': 'Work Date *',
    'jobs.form.field_start_time': 'Start Time',
    'jobs.form.field_end_time': 'End Time',
    'jobs.form.field_daily_wage': 'Daily Wage (₫) *',
    'jobs.form.field_slots_total': 'Slots *',
    'jobs.form.field_status': 'Status',
    'jobs.form.field_description': 'Description',
    'jobs.form.save_new': 'Create',
    'jobs.form.save_edit': 'Save Changes',
    'jobs.form.saving': 'Saving...',
    'jobs.form.save_failed': 'Save failed',
    'jobs.form.loading': 'Loading...',

    'companies.title': 'Company Management',
    'companies.subtitle': 'Manage construction companies linked to sites',
    'companies.new': '+ New Company',
    'companies.empty': 'No companies registered',
    'companies.first_register': '+ Register First Company',
    'companies.total': 'Total {n} companies',
    'companies.col_name': 'Company Name',
    'companies.col_reg_no': 'Business Reg No.',
    'companies.col_contact': 'Contact',
    'companies.col_phone': 'Phone',
    'companies.col_sites': 'Sites',
    'companies.col_signature': 'Signature',
    'companies.col_registered': 'Registered',
    'companies.sites_suffix': '',
    'companies.registered': 'Company registered',
    'companies.confirm_delete': 'Delete this company?',
    'companies.modal.edit_title': 'Edit Company',
    'companies.modal.create_title': 'Register New Company',
    'companies.modal.name': 'Company Name *',
    'companies.modal.reg_no': 'Business Reg No.',
    'companies.modal.contact_name': 'Contact Name',
    'companies.modal.contact_phone': 'Contact Phone',
    'companies.modal.contact_email': 'Contact Email',
    'companies.modal.save_edit': 'Save Changes',
    'companies.modal.save_create': 'Register',
    'companies.modal.saving': 'Saving...',
    'companies.detail.back': '← Back to Companies',
    'companies.detail.reg_no_label': 'Business Reg No.: ',
    'companies.detail.contact': 'Contact',
    'companies.detail.phone': 'Phone',
    'companies.detail.email': 'Email',
    'companies.detail.linked_sites': 'Linked Sites',
    'companies.detail.linked_sites_suffix': '',
    'companies.detail.signature': 'Company Signature / Seal',
    'companies.detail.signature_alt': 'Company Signature',
    'companies.detail.no_signature': 'No signature registered',
    'companies.detail.reg_cert': 'Business Registration Certificate',
    'companies.detail.view_reg_cert': '📄 View Registration Certificate',
    'companies.load_error': 'Failed to load company info',
    'companies.seal.upload': 'Upload Image',
    'companies.seal.change': 'Change Image',
    'companies.seal.drop_hint': 'Click to upload image',
    'companies.seal.uploaded': 'Seal/signature registered',
    'companies.seal.upload_failed': 'Upload failed. Please try again.',
    'companies.seal.deleted': 'Seal/signature deleted',
    'companies.seal.confirm_delete': 'Delete the seal/signature image?',

    'test_accounts.title': 'Test Account Management',
    'test_accounts.subtitle': 'Manage phone numbers that can log in with fixed OTP (000000)',
    'test_accounts.add': '+ Add Test Account',
    'test_accounts.empty': 'No test accounts registered',
    'test_accounts.otp_hint': 'Phone numbers registered as test accounts can log in using OTP "000000".',
    'test_accounts.col_phone': 'Phone',
    'test_accounts.col_name': 'Name',
    'test_accounts.col_role': 'Role',
    'test_accounts.col_status': 'Status',
    'test_accounts.col_created': 'Created',
    'test_accounts.role_worker': 'Worker',
    'test_accounts.role_manager': 'Manager',
    'test_accounts.confirm_delete': 'Delete this test account?',
    'test_accounts.deleted': 'Test account deleted',
    'test_accounts.created': 'Test account added',
    'test_accounts.error_phone_required': 'Please enter a phone number',
    'test_accounts.error_create_failed': 'Failed to add',
    'test_accounts.add_modal.title': 'Add Test Account',
    'test_accounts.add_modal.phone': 'Phone Number',
    'test_accounts.add_modal.name': 'Name',
    'test_accounts.add_modal.name_placeholder': 'e.g. Test Worker',
    'test_accounts.add_modal.role': 'Role',
    'test_accounts.add_modal.submit': 'Add',

    'login.brand': '가다 VN',
    'login.error_credentials': 'Incorrect username or password.',
    'login.logout_success': 'Logged out.',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.submit': 'Log In',
    'login.submitting': 'Logging in...',

    'admin_users.title': 'Admin Account Management',
    'admin_users.subtitle': 'Set menu permissions and invite accounts by email',
    'admin_users.invite': '+ Invite Account',
    'admin_users.col_email': 'Email / Name',
    'admin_users.col_role': 'Role',
    'admin_users.col_permissions': 'Menu Permissions',
    'admin_users.col_status': 'Status',
    'admin_users.col_last_login': 'Last Login',
    'admin_users.me': 'Me',
    'admin_users.status_active': 'Active',
    'admin_users.status_invited': 'Invited',
    'admin_users.status_disabled': 'Disabled',
    'admin_users.role_super_admin': 'Super Admin',
    'admin_users.role_admin': 'Admin',
    'admin_users.role_viewer': 'Viewer',
    'admin_users.action_edit_permissions': 'Edit Permissions',
    'admin_users.action_reset_password': 'Reset Password',
    'admin_users.action_resend': 'Resend',
    'admin_users.action_disable': 'Disable',
    'admin_users.confirm_disable': 'Disable this account?',
    'admin_users.disabled': 'Disabled',
    'admin_users.action_delete': 'Delete',
    'admin_users.confirm_delete': 'Permanently delete this account? This action cannot be undone.',
    'admin_users.deleted': 'Account deleted',
    'admin_users.invite_issued': 'Invite link issued',
    'admin_users.permissions_saved': 'Permissions saved',
    'admin_users.password_changed': 'Password changed',
    'admin_users.invite_modal.title': 'Invite Admin Account',
    'admin_users.invite_modal.invite_done': 'Invite Link Issued',
    'admin_users.invite_modal.invite_instruction': 'Send the invite link to',
    'admin_users.invite_modal.invite_link_label': 'Invite Link (valid 7 days)',
    'admin_users.invite_modal.copy': 'Copy',
    'admin_users.invite_modal.close': 'Close',
    'admin_users.invite_modal.email': 'Email *',
    'admin_users.invite_modal.name': 'Name',
    'admin_users.invite_modal.name_placeholder': 'John Doe',
    'admin_users.invite_modal.role': 'Role *',
    'admin_users.invite_modal.permissions': 'Menu Access Permissions',
    'admin_users.invite_modal.submit': 'Issue Invite Link',
    'admin_users.invite_modal.submitting': 'Processing...',
    'admin_users.invite_modal.invite_failed': 'Invite failed',
    'admin_users.invite_modal.email_sent': 'Invite email sent',
    'admin_users.invite_modal.email_not_sent': 'Email delivery failed — please copy and share the link below',
    'admin_users.permissions_modal.title': 'Edit Permissions',
    'admin_users.permissions_modal.role': 'Role',
    'admin_users.permissions_modal.permissions': 'Menu Access Permissions',
    'admin_users.permissions_modal.save': 'Save',
    'admin_users.permissions_modal.saving': 'Saving...',
    'admin_users.permissions_modal.save_failed': 'Save failed',
    'admin_users.reset_pw_modal.title': 'Reset Password',
    'admin_users.reset_pw_modal.new_password': 'New Password',
    'admin_users.reset_pw_modal.new_password_placeholder': 'Min. 8 characters',
    'admin_users.reset_pw_modal.confirm': 'Confirm Password',
    'admin_users.reset_pw_modal.submit': 'Reset Password',
    'admin_users.reset_pw_modal.submitting': 'Changing...',
    'admin_users.reset_pw_modal.error_mismatch': 'Passwords do not match',
    'admin_users.reset_pw_modal.error_min_length': 'Password must be at least 8 characters',
    'admin_users.reset_pw_modal.change_failed': 'Change failed',
    'admin_users.menu.dashboard': '📊 Dashboard',
    'admin_users.menu.managers': '👔 Manager Approval',
    'admin_users.menu.workers': '👷 Worker Management',
    'admin_users.menu.jobs': '🏗️ Job Management',
    'admin_users.menu.sites': '🏢 Site Management',
    'admin_users.menu.notifications': '🔔 Send Notifications',
    'admin_users.menu.admin_users': '🔑 Admin Accounts',

    'worker_detail.not_found': 'Worker not found',
    'worker_detail.manager_badge': 'Manager',
    'worker_detail.id_verified': 'ID Verified',
    'worker_detail.id_unverified': 'Unverified',
    'worker_detail.id_verified_badge': 'Verified',
    'worker_detail.id_unverified_badge': 'Unverified',
    'worker_detail.profile_complete': 'Profile Complete',
    'worker_detail.id_verified_check': 'ID Verified',
    'worker_detail.confirm_deactivate': 'Delete this worker? This action cannot be undone.',
    'worker_detail.deactivate_failed': 'Delete failed',
    'worker_detail.save_success': 'Saved.',
    'worker_detail.save_failed': 'Save failed. Please try again.',
    'worker_detail.skills_saved': 'Trade skills saved.',
    'worker_detail.tab_basic': 'Basic Info',
    'worker_detail.tab_docs': 'ID / Documents',
    'worker_detail.tab_bank': 'Bank / Payment',
    'worker_detail.tab_trades': 'Trades / Skills',
    'worker_detail.tab_manager': 'Manager',
    'worker_detail.tab_misc': 'Other',
    'worker_detail.tab_contracts': 'Contracts',
    'worker_detail.contracts_loading': 'Loading...',
    'worker_detail.contracts_empty': 'No contracts found.',
    'worker_detail.contracts_error': 'Could not load contracts.',
    'worker_detail.contract_status_pending_worker_sign': 'Awaiting Worker Signature',
    'worker_detail.contract_status_pending_manager_sign': 'Awaiting Company Signature',
    'worker_detail.contract_status_fully_signed': 'Fully Signed',
    'worker_detail.contract_status_void': 'Void',
    'worker_detail.contract_job_title': 'Job',
    'worker_detail.contract_site': 'Site',
    'worker_detail.contract_work_date': 'Work Date',
    'worker_detail.contract_daily_wage': 'Daily Wage',
    'worker_detail.contract_worker_signed': 'Worker Signed',
    'worker_detail.contract_created_at': 'Created',
    'worker_detail.field_name': 'Name',
    'worker_detail.field_dob': 'Date of Birth',
    'worker_detail.field_gender': 'Gender',
    'worker_detail.field_gender_none': 'Not Selected',
    'worker_detail.field_gender_male': 'Male',
    'worker_detail.field_gender_female': 'Female',
    'worker_detail.field_gender_other': 'Other',
    'worker_detail.field_bio': 'Bio',
    'worker_detail.field_trade_id': 'Primary Trade ID',
    'worker_detail.field_experience': 'Experience (months)',
    'worker_detail.field_id_number': 'ID / Resident Number',
    'worker_detail.field_verified_at': 'Verified At',
    'worker_detail.unverified_date': 'Unverified',
    'worker_detail.attachments_title': 'Attached Images',
    'worker_detail.field_id_front': 'ID Front',
    'worker_detail.field_id_back': 'ID Back',
    'worker_detail.field_bank_book': 'Bank Passbook',
    'worker_detail.field_signature': 'Signature',
    'worker_detail.field_bank_name': 'Bank Name',
    'worker_detail.field_bank_account': 'Account Number',
    'worker_detail.trades_loading': 'Loading...',
    'worker_detail.trades_empty': 'No trades registered.',
    'worker_detail.trade_select': 'Select Trade',
    'worker_detail.experience_years_placeholder': 'Years',
    'worker_detail.experience_years_suffix': 'yr',
    'worker_detail.trade_add': '+ Add Trade',
    'worker_detail.manager_active': 'Manager Active',
    'worker_detail.approved_suffix': 'approved)',
    'worker_detail.field_company': 'Company',
    'worker_detail.field_contact_name': 'Contact Name',
    'worker_detail.manager_profile_link': 'View Manager Profile →',
    'worker_detail.no_manager': 'This worker has no manager privileges.',
    'worker_detail.promote_link': 'Promote to Manager →',
    'worker_detail.field_phone': 'Phone',
    'worker_detail.field_email': 'Email',
    'worker_detail.field_lat': 'Latitude (lat)',
    'worker_detail.field_lng': 'Longitude (lng)',
    'worker_detail.terms_accepted': 'Terms Accepted',
    'worker_detail.privacy_accepted': 'Privacy Policy Accepted',
    'worker_detail.field_joined': 'Joined',

    'manager_detail.not_found': 'Manager not found',
    'manager_detail.status_approved': 'Approved',
    'manager_detail.status_rejected': 'Rejected',
    'manager_detail.status_revoked': 'Revoked',
    'manager_detail.status_pending': 'Pending',
    'manager_detail.approve': 'Approve',
    'manager_detail.reject': 'Reject',
    'manager_detail.revoke': 'Revoke Access',
    'manager_detail.re_approve': 'Re-review (Approve)',
    'manager_detail.confirm_approve': 'Approve this manager?',
    'manager_detail.confirm_revoke': 'Revoke this manager\'s access?',
    'manager_detail.reject_reason_label': 'Rejection Reason',
    'manager_detail.reject_reason_placeholder': 'Enter rejection reason',
    'manager_detail.reject_confirm': 'Confirm Rejection',
    'manager_detail.reject_reason_required': 'Please enter a rejection reason.',
    'manager_detail.site_assigned': 'Site assigned.',
    'manager_detail.site_assign_failed': 'Site assignment failed.',
    'manager_detail.site_unassigned': 'Site assignment removed.',
    'manager_detail.site_unassign_failed': 'Failed to remove assignment.',
    'manager_detail.revoked': 'Access revoked.',
    'manager_detail.revoke_failed': 'Processing failed.',
    'manager_detail.save_success': 'Saved.',
    'manager_detail.save_failed': 'Save failed. Please try again.',
    'manager_detail.tab_basic': 'Basic Info',
    'manager_detail.tab_site': 'Business Info',
    'manager_detail.tab_docs': 'Document Check',
    'manager_detail.tab_approval': 'Approval Info',
    'manager_detail.tab_sites': 'Site Assignment',
    'manager_detail.field_business_type': 'Business Type',
    'manager_detail.business_type_individual': 'Individual',
    'manager_detail.business_type_corporate': 'Corporate',
    'manager_detail.field_company_name': 'Company Name',
    'manager_detail.field_representative': 'Representative',
    'manager_detail.field_representative_dob': 'Representative DOB',
    'manager_detail.field_representative_gender': 'Representative Gender',
    'manager_detail.field_gender_none': 'Not Selected',
    'manager_detail.field_gender_male': 'Male',
    'manager_detail.field_gender_female': 'Female',
    'manager_detail.field_gender_other': 'Other',
    'manager_detail.field_contact_phone': 'Contact Phone',
    'manager_detail.field_reg_number': 'Business Reg. Number',
    'manager_detail.field_contact_address': 'Business Address',
    'manager_detail.field_province': 'Province',
    'manager_detail.field_first_site_name': 'First Site Name',
    'manager_detail.field_first_site_address': 'First Site Address',
    'manager_detail.docs_title': 'Attached Documents',
    'manager_detail.doc_reg_cert': 'Business Registration Certificate',
    'manager_detail.doc_signature': 'Signature',
    'manager_detail.doc_profile_picture': 'Profile Picture',
    'manager_detail.approval_status_label': 'Approval Status',
    'manager_detail.approval_date': 'Approved At',
    'manager_detail.rejection_reason': 'Rejection Reason',
    'manager_detail.joined': 'Joined',
    'manager_detail.verified_phone': 'Phone (Verified)',
    'manager_detail.sites_assigned': 'Assigned Sites',
    'manager_detail.sites_none': 'No sites assigned.',
    'manager_detail.sites_none_hint': 'Select a site below to assign.',
    'manager_detail.site_status_active': 'Active',
    'manager_detail.site_status_paused': 'Paused',
    'manager_detail.site_status_completed': 'Completed',
    'manager_detail.assigned_date': 'Assigned: ',
    'manager_detail.unassign': 'Remove',
    'manager_detail.unassigning': 'Removing...',
    'manager_detail.site_add': 'Add Site',
    'manager_detail.site_search_placeholder': 'Search by site name or address...',
    'manager_detail.site_no_results': 'No results or all sites already assigned.',
    'manager_detail.site_no_sites': 'No sites registered.',
    'manager_detail.assign': 'Assign',
    'manager_detail.assigning': 'Assigning...',
    'manager_detail.site_loading': 'Loading...',

    'notifications.title': 'Notification Management',
    'notifications.subtitle': 'Send push notifications and SMS to workers and managers.',
    'notifications.flash_sent': 'Notification sent.',
    'notifications.flash_scheduled': 'Notification scheduled.',
    'notifications.flash_cancelled': 'Schedule cancelled.',
    'notifications.flash_error': 'An error occurred.',
    'notifications.form_title': '✍️ Compose Notification',
    'notifications.field_title': 'Notification Title *',
    'notifications.field_title_placeholder': 'e.g. New job posting available',
    'notifications.field_body': 'Notification Body *',
    'notifications.field_body_placeholder': 'Enter the message body (max 300 characters)',
    'notifications.field_channel': 'Send Channel *',
    'notifications.sms_warning': '⚠️ SMS is sent to registered phone numbers. In dev, it logs to console.',
    'notifications.field_target': 'Recipients',
    'notifications.target_role': 'All by Role',
    'notifications.target_users': 'Select Individual Users',
    'notifications.field_target_role': 'Target Role',
    'notifications.role_worker_all': 'All Workers',
    'notifications.role_manager_all': 'All Managers',
    'notifications.field_user_search': 'Search & Select Users',
    'notifications.user_search_placeholder': 'Search by name or phone...',
    'notifications.role_worker': 'Worker',
    'notifications.role_manager': 'Manager',
    'notifications.role_all': 'All',
    'notifications.selected_users': 'Selected ({n} users)',
    'notifications.field_send_time': 'Send Time',
    'notifications.send_now': 'Send Now',
    'notifications.send_schedule': 'Schedule',
    'notifications.field_schedule_at': 'Schedule Time',
    'notifications.submit_now': '🚀 Send Now',
    'notifications.submit_schedule': '📅 Schedule',
    'notifications.submitting': 'Sending...',
    'notifications.alert_no_channel': 'Please select a send channel',
    'notifications.alert_no_users': 'No target users found',
    'notifications.push_label': 'Push Notification (FCM)',
    'notifications.push_desc': 'Sent to users with the app installed via FCM token.',
    'notifications.sms_label': 'SMS',
    'notifications.sms_desc': 'Sent to all users with a registered phone number.',
    'notifications.channel_guide': '📊 Channel Guide',
    'notifications.scheduled_title': '📅 Scheduled Notifications',
    'notifications.no_scheduled': 'No scheduled notifications',
    'notifications.status_pending': 'Pending',
    'notifications.status_sent': 'Sent',
    'notifications.status_cancelled': 'Cancelled',
    'notifications.status_failed': 'Failed',
    'notifications.target_worker_suffix': 'workers',
    'notifications.target_manager_suffix': 'managers',
    'notifications.cancel_schedule': 'Cancel',
    'notifications.confirm_cancel_schedule': 'Cancel this scheduled notification?',

    'promote_worker.title': 'Directly Assign Manager',
    'promote_worker.subtitle': 'Search for a worker and assign them as manager immediately.',
    'promote_worker.warning': '⚠️ Only use this when verification is complete.',
    'promote_worker.warning_body': 'The worker will immediately gain manager access.',
    'promote_worker.section1': '1. Search Worker',
    'promote_worker.search_placeholder': 'Search by name or phone',
    'promote_worker.search_btn': 'Search',
    'promote_worker.searching': 'Searching...',
    'promote_worker.loading_detail': 'Loading worker info...',
    'promote_worker.id_verified': 'ID Verified',
    'promote_worker.id_unverified': 'Unverified',
    'promote_worker.select_arrow': 'Select →',
    'promote_worker.reselect': 'Reselect',
    'promote_worker.section2': '2. Enter Manager Info',
    'promote_worker.field_business_type': 'Business Type',
    'promote_worker.business_individual': 'Individual',
    'promote_worker.business_corporate': 'Corporate',
    'promote_worker.field_representative': 'Representative Name',
    'promote_worker.field_company': 'Company Name',
    'promote_worker.field_dob': 'Date of Birth',
    'promote_worker.field_gender': 'Gender',
    'promote_worker.gender_none': 'Not Selected',
    'promote_worker.gender_male': 'Male',
    'promote_worker.gender_female': 'Female',
    'promote_worker.gender_other': 'Other',
    'promote_worker.field_reg_number': 'Business Reg. Number',
    'promote_worker.field_phone': 'Contact Phone',
    'promote_worker.field_address': 'Business Address',
    'promote_worker.field_region': 'Region',
    'promote_worker.field_first_site': 'First Site Name',
    'promote_worker.field_first_site_address': 'Site Address',
    'promote_worker.submit': 'Assign as Manager',
    'promote_worker.submitting': 'Processing...',
    'promote_worker.success_title': 'Manager Assignment Complete',
    'promote_worker.success_body': 'has been assigned as manager.',
    'promote_worker.view_managers': 'View Manager List',
    'promote_worker.representative_required': 'Representative name is required.',
    'promote_worker.search_failed': 'Search failed',
    'promote_worker.no_results': 'No results found. Please check the name or phone number.',
    'promote_worker.load_failed': 'Failed to load worker info.',
    'promote_worker.no_user_id': 'Could not find user_id for this worker.',
    'promote_worker.submit_failed': 'Assignment failed.',
  },
}

export function useAdminTranslation() {
  const { locale } = useLanguage()
  const t = (key: string) => ADMIN_TRANSLATIONS[locale]?.[key] ?? key
  return { t, locale }
}
